### ISSUE TITLE
Confusing behavior when package depends on a specific Cabal version

### ISSUE THREAD

**Issue by pikajude** [haskell-CI/haskell-ci#134]
I have a project that's pinned to Cabal 2.0.* because it parses Cabal files and requires a specific parser version.

There are two things that were confusing for me when I started setting up a haskell-ci travis file for my repo:

1. Building with the INSTALLED constraint will only work on GHC 8.2.2, where the installed Cabal version happens to match the one I requested
2. Even building without INSTALLED, the GHCHEAD cabal config file specifies `allow-newer: *:Cabal`, which breaks my build because, as far as I understand it, it tries to build with Cabal 2.1.0.0 (which is installed during the setup process). Obviously my package doesn't yet compile with Cabal 2.1 as the API has changed quite a bit.

Is there a straightforward way to make those two cases work for packages that require a specific version for only a single builtin package?

**Comment by phadej** [comment]
1. You can disable that check with `--no-installed`, there is no way to filter out only single package.
2. Don't test with GHC-HEAD / GHC-8.4 :) Even if `Cabal-2.0` compiles with GHC-HEAD / GHC-8.4, old Cabal + new GHC is not a good idea in general.

**Comment by phadej** [comment]
See this package. You can pin all but `Cabal` ghc boot libs with `installed: +all -Cabal`.
