### ISSUE TITLE
No GHC 8.4.1 build for Ubuntu 17.04

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#139]
Currently, https://launchpad.net/~hvr/+archive/ubuntu/ghc has a GHC 8.4.1 build for 14.04, 16.04, and 17.10. However, for 17.04 (the Ubuntu version I happen to be using), the most recent GHC version is 8.4.0.20171222+git.0.c6cf13c-7. Is it possible to trigger a 8.4.1 build for 17.04?

**Comment by hvr** [comment]
Unfortunately, Ubuntu stops accepting new uploads for releases which are beyond their EOL'ed (c.f. https://wiki.ubuntu.com/Releases) and if the disk quota gets tight you get asked to remove artifacts that have EOL'ed before being granted more disk quota. These two factors combined rule out builds for 17.04.

**Comment by RyanGlScott** [comment]
Darn :(
