### ISSUE TITLE
Should GHC versions be queried from somewhere?

### ISSUE THREAD

**Issue by merijn** [haskell-CI/haskell-ci#143]
Right now the script stores a bunch of supported versions in the source code, which means updating tests to run on newer GHCs involves updating the script, etc. I think it'd be more convenient to query GHC versions from somewhere, but I'm unsure how doable that is without incurring a ton of dependencies.

**Comment by phadej** [comment]
Being able to generate stuff without accessing network is IMO a must feature.

**Comment by merijn** [comment]
@phadej sure, I'm not saying updating that should be *required* or that I'm opposed to embedding a set of GHC versions into the script. I'm just annoyed if I have to manually update my checkout, rebuild, etc. all to be able to generate stuff for new GHC versions.

So more like a flag (or just blindly trying) to query a more recent GHC list and using that, falling back to whatever is in the script if there's no network. Seems like best of both worlds?

**Comment by phadej** [comment]
script itself is updated more often than GHC list, so I don't see a benefit right now.
