### ISSUE TITLE
Test script broken for GHC head

### ISSUE THREAD

**Issue by merijn** [haskell-CI/haskell-ci#144]
The travis script first removes the existing cabal.project file, then tries to add the head overlay for hackage here: https://github.com/haskell-CI/haskell-ci/blob/master/make_travis_yml_2.hs#L748-L767

This call to `new-update` fails because there is no cabal.project. This probably works for trivial repo's because the existence of a `.cabal` file will trigger the implicit cabal.project. However on repos that do not have a cabal file in the root this always fails. See https://travis-ci.org/merijn/broadcast-chan/jobs/356918081

Either the head overlay should be moved prior to the cabal.project or something else should be done to avoid breaking the tests.

**Comment by phadej** [comment]
I'd rather fix it in `cabal`: https://github.com/haskell/cabal/issues/5096 it's not biggie.

**Comment by merijn** [comment]
Pretty sure this is already fixed.
