### ISSUE TITLE
GHC 8.4.1 from the Ubuntu PPA is at the wrong commit

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#146]
Currently, the official GHC 8.4.1 bindist from https://www.haskell.org/ghc/download_ghc_8_4_1.html is at commit https://github.com/ghc/ghc/commit/f31c40efdc918bc9da8a325327ba5a472bd6ea9e:

```
$ ~/Software/ghc-8.4.1/bin/ghc --info
 [
...
 ,("Project Git commit id","f31c40efdc918bc9da8a325327ba5a472bd6ea9e")
...
 ]
```

However, the GHC 8.4.1 from https://launchpad.net/~hvr/+archive/ubuntu/ghc is at a different commit, https://github.com/ghc/ghc/commit/0a3e2f324dbd525d626ebd3d97e8ffa1cf2f0ffb:

```
$ /opt/ghc/8.4.1/bin/ghc --info      
 [
...
 ,("Project Git commit id","0a3e2f324dbd525d626ebd3d97e8ffa1cf2f0ffb")
...
 ]
```

**Comment by hvr** [comment]
It's a known issue; the trouble was that originally a different commit was tagged and pushed designating GHC 8.4.1; and that's what my scripting picked up. It's not trivial to correct this now (and it's not the only inconsistency that occured in GHC 8.4.1...). Anyway, GHC 8.4.2 is around the corner, and hopefully in the future published git release tags won't be moved around anymore... :-)

**Comment by RyanGlScott** [comment]
Nevertheless, it's still an extremely huge inconvenience in practice. I'd strongly urge you to fix this if there is a way to make this happen.

**Comment by hvr** [comment]
What's specifically the "extremely huge inconvenience" you're referring to?

The trouble I have is that fixing this will cost me likely *at least* a couple hours to implement this if everything works (I'd have to manually modify the packaging to include a reverse patch, and each trial&error attempt via launchpad takes about half an hour... not fun); but this also breaks everyone who started using GHC 8.4.1 packages from my PPA, as they'd end up with an inconsistent pkg-db, as in general packages compiled by a different commits of GHC are not compatible with each other; I'd feel more comfortable if we had https://github.com/haskell/cabal/issues/5116 already implemented, as that would have taken care of that. Consequently, there's also significant inconvenience associated with trying correct this.

**Comment by RyanGlScott** [comment]
The inconvenience is that the commits ( https://github.com/ghc/ghc/compare/f31c40efdc918bc9da8a325327ba5a472bd6ea9e...0a3e2f324dbd525d626ebd3d97e8ffa1cf2f0ffb ) separating the bindist and the PPA version are not insignificant. There are several bugs which occur in one that do not occur in the other as a result, which makes testing 8.4.1 for certain protects a nightmare.

**Comment by hvr** [comment]
@RyanGlScott fwiw, GHC 8.4.2 RC1 just became available yesterday.

**Comment by RyanGlScott** [comment]
It doesn't appear that this will ever be fixed, so closing.
