### ISSUE TITLE
Print out all dependencies and versions

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#152]
The `old-build`–based Travis script had a nice feature where it would print out every configured dependency and their version numbers ([example](https://travis-ci.org/scotty-web/scotty/jobs/363512116#L639)), which was incredibly helpful in diagnosing build errors resulting from certain downstream dependencies. It would be nice if the `new-build`–based Travis script could do the same.

**Comment by hvr** [comment]
We have two options; either `cabal new-freeze` and dump out the file, or use `cabal-plan` to pretty-print the install-plan, possibly in a tree style (until `cabal` proper learns this as well)

**Comment by phadej** [comment]
I think `new-freeze` is nice and simple solution.
