### ISSUE TITLE
Which version bounds should be relaxed on GHC HEAD builds?

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#160]
I recently experienced a GHC HEAD build failure (see [this Travis build](https://travis-ci.org/goldfirere/singletons/jobs/392267174#L690)). It turns out that the culprit was that the build plan was trying to install an older version of `stm`, as a downstream dependency's upper version bounds on `stm` prevented the build plan from picking the more recent `stm` version that was bundled with HEAD.

This leaves me wondering: should the generated `.travis.yml` script ignore upper version bounds for all boot libraries like `stm`? Currently, the script chooses these particular libraries to `allow-newer` for:

https://github.com/haskell-CI/haskell-ci/blob/67b96439f4312b29de8125f9cb19bad741cfb4bc/make_travis_yml_2.hs#L768

That is, `base`, `ghc`, `template-haskell`, and `Cabal`. It's unclear to me if there is a particular rhyme or reason as to why these are the only ones given special treatment. Should this special treatment extend to `stm`? Or `unix`, which also has a more recent major version bundled with GHC HEAD? Or any other boot library?

**Comment by phadej** [comment]
I just relaxed packages which were bumped in 8.4. Not sure if can relax everything, is time-1.9 in HEAD?

**Comment by RyanGlScott** [comment]
In terms of libraries that are bundled with GHC HEAD that have had major version bumps since GHC 8.4, the only new ones at the moment are `stm` and `unix`. But it's possible that there will be other major version bumps in the future for other packages, which might suggest that we should preemptively allow them?

**Comment by RyanGlScott** [comment]
My personal inclination is to simply `allow-newer` for each library in this list:

```
$ /opt/ghc/8.4.3/bin/ghc-pkg list
/opt/ghc/8.4.3/lib/ghc-8.4.3/package.conf.d
    Cabal-2.2.0.1
    array-0.5.2.0
    base-4.11.1.0
    binary-0.8.5.1
    bytestring-0.10.8.2
    containers-0.5.11.0
    deepseq-1.4.3.0
    directory-1.3.1.5
    filepath-1.4.2
    ghc-8.4.3
    ghc-boot-8.4.3
    ghc-boot-th-8.4.3
    ghc-compact-0.1.0.0
    ghc-prim-0.5.2.0
    ghci-8.4.3
    haskeline-0.7.4.2
    hpc-0.6.0.3
    integer-gmp-1.0.2.0
    mtl-2.2.2
    parsec-3.1.13.0
    pretty-1.1.3.6
    process-1.6.3.0
    rts-1.0
    stm-2.4.5.0
    template-haskell-2.13.0.0
    terminfo-0.4.1.1
    text-1.2.3.0
    time-1.8.0.2
    transformers-0.5.5.0
    unix-2.7.2.2
    xhtml-3000.2.2.1
```

Does that sound agreeable, @phadej?

**Comment by phadej** [comment]
Shortly: no, otherwise `time-1.9` will be picked into "default" install plans. I'll make a change to  automatically include everything in global DB, except time (and possible other not yet bumped dependencies).

**Comment by RyanGlScott** [comment]
What is special about `time` that warrant special treatment?

**Comment by phadej** [comment]
Actually, i'd just change the way script works to have `pkg installed` constraints by default. (And have "free" plan builds optionally, I'll make an example PR to `constraints`)

**Comment by RyanGlScott** [comment]
Alright. I don't quite understand what you're getting at, but I'll reserve judgment until I see this in action.

**Comment by phadej** [comment]
If we allow newer `time` without constraining it to the installed version, 1.9.1 ie. non-installed) *might* be picked. That's not what we want.

**Comment by RyanGlScott** [comment]
Oh, _right_.

(For idiots like me who need it spelled out: there is a version of `time` on Hackage that's even newer than the one shipped with GHC HEAD, so blindly allowing newer for all of these packages would result in using a non-bundled version of `time`.)

**Comment by RyanGlScott** [comment]
@phadej came up with a much cleaner solution for this in https://github.com/haskell-CI/haskell-ci/pull/161.
