### ISSUE TITLE
What is the purpose of the "build with installed constraints" step?

### ISSUE THREAD

**Issue by parsonsmatt** [haskell-CI/haskell-ci#162]
I've got [a PR for `acid-state` open](https://github.com/acid-state/acid-state/pull/94) that was failing CI on this step:

```
  # Build with installed constraints for packages in global-db
 - if $INSTALLED; then echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks $(${HCPKG} list --global --simple-output --names-only | sed 's/\([a-zA-Z0-9-]\{1,\}\) */--constraint="\1 installed" /g') all | sh; else echo "Not building with installed constraints"; fi
```

But only on GHC 7.6.3. The error message is ([linked here](https://travis-ci.org/acid-state/acid-state/jobs/397533010#L818)):

```
cabal: Could not resolve dependencies:
[__0] trying: acid-state-0.15.0 (user goal)
[__1] next goal: unix (dependency of acid-state)
[__1] rejecting: unix-2.6.0.1/installed-f12... (conflict: acid-state =>
bytestring>=0.10.2, unix => bytestring==0.10.0.2/installed-4f9...)
[__1] rejecting: unix-2.7.2.2, unix-2.7.2.1, unix-2.7.2.0, unix-2.7.1.0,
unix-2.7.0.1, unix-2.7.0.0, unix-2.6.0.1, unix-2.6.0.0, unix-2.5.1.1,
unix-2.5.1.0, unix-2.5.0.0, unix-2.4.2.0, unix-2.4.1.0, unix-2.4.0.2,
unix-2.4.0.1, unix-2.4.0.0, unix-2.3.2.0, unix-2.3.1.0, unix-2.3.0.0,
unix-2.2.0.0, unix-2.0 (constraint from command line flag requires installed
instance)
[__1] fail (backjumping, conflict set: acid-state, unix)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: acid-state, unix
```

If I omit this build step in the travis file, [then it builds just fine](https://travis-ci.org/acid-state/acid-state/builds/397547820).

What's the purpose of this step? How can we prevent it from failing like this?

**Comment by phadej** [comment]
- GHC-7.6.3 is bundled with `bytestring-0.10.0.2`
- `acid-state` master has `bytestring >= 0.10.2` (bundled only with GHC-7.8, see https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory)

So on GHC-7.6.3 there aren't an install plan with libraries bundled with GHC. That might be a problem for a maintainer, or not. 

Rectangular boxes are "to be built" dependencies, octagons are bundled packages, and round-corner packages is the local `acid-state`: 

![image](https://user-images.githubusercontent.com/51087/42002934-c703e8b2-7a71-11e8-9e1d-7b43b31dc33b.png)

E.g. upgrading `containers` is bad idea, if you use `template-haskell`, as that's not re-installable package. In general if your install plan will loop to `ghc` (i.e. if your test-suites have `doctest` dep) you'll be in trouble.

It's a choice for each maintainer to make, whether they want to support some versions of compilers, even their package isn't buildable with bundled dependencies.

With that `make_travis_yml_2.hs`  script you can either use `env: INSTALLED=false` to omit the step for some GHC, or `--no-installed` to omit that step entirely.

Current version has `installed` constraints by default, and you can disable their use by using `env: 
NOINSTALLEDCONSTRAINTS=true`. I have forgotten to add a cli flag to disable that functionality entirely. Will add it soon.

**Comment by parsonsmatt** [comment]
Hmm, that's good to know. Does that mean that `acid-state` is incompatible with GHC <7.8?

**Comment by phadej** [comment]
It's not incompatible.. It's might be difficult to use in some situations, and I think maintainers should be aware of it.

For example having `containers >= 0.6` today is clearly a bad idea (there aren't GHC bundling it yet), though you can use it for simple packages (i.e. which don't use `template-haskell`).

Yet, For `bytestring` + GHC-7.6.3 it's probably ok. But then maintainers have to explicitly mention that in their CI setup. (I have plans to make per-GHC configuration available through cli interface, so you don't need to manually edit `.travis.yml`).

---

FWIW, there's an install plan for `acid-state-0.14.3` with GHC-7.0.4. It fails with

```
src/Data/Acid/Core.hs:55:8:
    Could not find module `Data.Typeable.Internal':
      Use -v to see a list of the files searched for.
```

that's wrong lower bound on `base`. I recommend to keep it in sync with the versions of GHC maintainers are supporting & testing with.

I managed to compile acid-state with GHC-7.4.2, but does it really work? Will maintainers appreciate a bug report, if I find out it doesn't?

**Comment by phadej** [comment]
Anecdotally, e.g. `constraints` had too tight lower bound on `binary` for apparently no reason. We found it using this. (That causes latest `constraints` not to be picked by its reverse dependencies which use `doctest` in test-suite).

**Comment by parsonsmatt** [comment]
The `safecopy` maintainers indicated that [they'd be fine dropping 7.8 support](https://github.com/acid-state/safecopy/pull/65#issuecomment-396997549), so it's likely that `acid-state` would be OK with dropping support for at least 7.8.

I definitely appreciate those sorts of reports on the libraries I support, but I cannot speak for the `acid-state` maintainers.

**Comment by phadej** [comment]
Good. @parsonsmatt Can I close this once I made a cli option? (I'd like to keep this open until that, as a reminder).

**Comment by hvr** [comment]
Fwiw, if acid-state drops support for older GHCs, then hackage-server won't upgrade to them in the near future...

**Comment by stepcut** [comment]
@hvr How old of a GHC do you need support for? 

Rather than make a full fork of acid-state, I'd rather have an upstream branch that we can backport any essential bugfixes to and then cut an official release to upload to hackage.

I am also not expecting any bug fixes -- if there was a problem, we probably would have encountered it by now. The work on acid-state now is to add new features.

**Comment by phadej** [comment]
One can specify `--installed=-all` to say "-all" (i.e. none) packages need to be of installed versions
