### ISSUE TITLE
Flag to always enable NOINSTALLEDCONSTRAINTS

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#163]
I'm currently upgrading my Travis scripts for GHC boot libraries like `mtl`, `stm`, and `unix`, and discovering that they often [break due](https://travis-ci.org/haskell/mtl/builds/398848494) to `NOINSTALLEDCONSTRAINTS` not being on. The most reliable fix appears to be to use `NOINSTALLEDCONSTRAINTS` everywhere, but this requires me to [manually place `NOINSTALLEDCONSTRAINTS=true`](https://github.com/haskell/mtl/commit/6f33b3368f99581438f0cbd1a6900d14b4f96172) on every single entry of the matrix configuration.

A flag that would enable the use of `NOINSTALLEDCONSTRAINTS` globally would significantly help in this endeavor.

**Comment by phadej** [comment]
Would it be enough to filter the package(s) from package list in https://github.com/haskell/mtl/commit/6f33ba3368f99581438f0cbd1a6900d14b4f96172#diff-354f30a63fb0907d4ad57269548329e3R120 ?

**Comment by RyanGlScott** [comment]
I'm not sure which packages you're referring to (also, that link is dead).

**Comment by phadej** [comment]
The file generates `cabal.project.local` which has

```
constraints: base installed
constraints: stm installed
...
```

Would it be enough to filter `stm` out of that list, when building `stm`

**Comment by RyanGlScott** [comment]
> Would it be enough to filter `stm` out of that list, when building `stm`

I have no idea. Is there a simple way to test this theory out?

**Comment by phadej** [comment]
@RyanGlScott could you try: https://github.com/haskell-CI/haskell-ci/tree/omit-local-package

**Comment by RyanGlScott** [comment]
I'm giving this a whirl on `mtl` now: https://travis-ci.org/haskell/mtl/builds/399714580

**Comment by RyanGlScott** [comment]
Unfortunately, that didn't appear to work: https://travis-ci.org/haskell/mtl/jobs/399714585

**Comment by RyanGlScott** [comment]
This was resolved in #164.
