### ISSUE TITLE
Flag to specify extra apt dependencies

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#167]
In `lens`'s `.travis.yml`, we need to [install `freeglut3-dev`](https://github.com/ekmett/lens/blob/794851d72c9c376246adbfe17103b5fb1dfb555a/.travis.yml#L41) in order to be able to build the examples. It would be convenient to be able to automate this.

**Comment by phadej** [comment]
Just add an argument `haskell-ci ... lens.cabal freeglut3-dev`

**Comment by phadej** [comment]
(I know it's not the best cli UX, but it's there)

**Comment by RyanGlScott** [comment]
Oops, that's what I get for not reading the `--help` output:

```
Usage: runghc make_travis_yml_2.hs [OPTIONS] <cabal-file | cabal.project> <extra-apt-packages...>
```

With emphasis on the `<extra-apt-packages...>` part :)
