### ISSUE TITLE
It's impossible to build without "installed" constraints

### ISSUE THREAD

**Issue by peti** [haskell-CI/haskell-ci#168]
The PR https://github.com/haskell-CI/haskell-ci/pull/161 broke the ability to run a build without any "installed" constraints, which is necessary for any package that depends on a recent version of `Cabal`, for instance, because older compilers won't have that version. With "installed" constraints in place, all those builds fail.

There used to be `--no-installed` to remedy that issue, but that flag has been removed.

**Comment by ygale** [comment]
I ran into this when I needed to use a recent `deepseq` even for older versions of GHC. I worked around it by hacking the generated `.travis.yaml` script to omit the constraint for `deepseq` (in two places in the script).

In my case, I would prefer to leave the `installed` constraints for all but `deepseq`. The `--no-installed` flag is a bit heavy handed. I'm not sure what a good UI for that would be. Ideally, we should parse through all the deps and omit the `installed` constraint for any GHC libs that have manually set constraints. But that could get pretty complex.

**Comment by phadej** [comment]
Now it's possible, `--installed` flag and `installed` options are now more flexible than it was
- `+all`: all packages existing in global package db have to stay with installed versions
- `-all`: none.
- `+all -Cabal` all but Cabal
- `-all +deepseq +binary` only deepseq and binary need to use installed versions

**Comment by peti** [comment]
This is a great solution. Thank you very much!

**Comment by phadej** [comment]
@peti you're welcome.

**Comment by fgaz** [comment]
What is the reason behind having +all as default? Why not -all? Is there some advantage in using packages from the global db? Is it just to explicitly test a configuration that would happen in the case of package managers that require global consistency?

**Comment by phadej** [comment]
> Is there some advantage in using packages from the global db?

Yes, we can catch when bounds are too restrictive to use GHC bundled versions of dependencies. I have a strict view that if a package claims to support GHC-x.y, then it's buildable without upgrading the bundled dependencies OR it is explicit about that (e.g. `haskell-ci` requires to upgrade `Cabal`, but nothing else).

**Comment by fgaz** [comment]
Makes sense, though I think this should be explained in the readme, since it might not be immediately obvious and it can cause unexpected faulures (I see there are multiple tickets asking about this).

I may open a PR later.
