### ISSUE TITLE
Could not find module ‘Distribution.PackageDescription.Parse’

### ISSUE THREAD

**Issue by chris-martin** [haskell-CI/haskell-ci#181]
I cloned this repo and ran `make_travis_yml.hs` as the "quick-start instructions" section in the README says, and I get this result:

```
/home/chris/haskell/haskell-ci/make_travis_yml.hs:14:1: error:
    Could not find module ‘Distribution.PackageDescription.Parse’
    Perhaps you meant
      Distribution.PackageDescription.Parsec (from Cabal-2.4.0.0)
      Distribution.PackageDescription.Check (from Cabal-2.4.0.0)
      Distribution.PackageDescription.Quirks (from Cabal-2.4.0.0)
    Use -v to see a list of the files searched for.
   |
14 | import           Distribution.PackageDescription.Parse (readPackageDescription)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is there a dependency installation step missing in the instructions maybe?

**Comment by hvr** [comment]
@chris-martin we're slowly moving away from the old instructions of running via `runghc`; can you try build the `.cabal` package instead?

**Comment by chris-martin** [comment]
Cool, that worked. I guess the instructions in the generated YAML comment need to be updated too? https://github.com/typeclasses/d10/blob/420a148b25c08e4172a1317bfc3ad5a5e713ce98/.travis.yml#L1-L9

**Comment by hvr** [comment]
@chris-martin oh... I just realised, you used the old v1 script; `runghc` might still have worked with the make_travis_yml_2.hs script until we refactor into a multi-module program

**Comment by chris-martin** [comment]
Ahhh I didn't notice the Hackage release. That makes it much easier, all I had to do was add it to my NixOS config :) https://github.com/chris-martin/home/commit/a324033cb9b254866da48bd8953ce777fbcd5fb5

**Comment by phadej** [comment]
This package moved from using `runghc`. Only a package now.
