### ISSUE TITLE
Use new-buld in step 4 of the README

### ISSUE THREAD

**Issue by fgaz** [haskell-CI/haskell-ci#190]
A friend of mine struggled to make it work, since it needs some globally-installed packages.

For example `cabal --project-file=path/to/haskell-ci/cabal.project new-run make-travis-yml -- your-package.cabal > .travis.yml` instead of (or in addition to) `path/to/haskell-ci/make_travis_yml.hs your-project.cabal > .travis.yml`

**Comment by RyanGlScott** [comment]
This issue is especially relevant now that `make_travis_yml.hs` is no more and that the _only_ way to build `haskell-ci` is by way of build tools.
