### ISSUE TITLE
8.6.2 support for Ubuntu Cosmic?

### ISSUE THREAD

**Issue by jrp2014** [haskell-CI/haskell-ci#191]
Herbert, it would be great if you could generate a ppa for Ubuntu Cosmic 18.10.  Thanks!

**Comment by hvr** [comment]
@jrp2014 it's on my radar! in the meantime the Bionic LTS should be binary compatible

**Comment by jrp2014** [comment]
Thanks.  (How) Can I install it without messing up my apt database for future upgrades?

**Comment by hvr** [comment]
@jrp2014 Since yesterday there's proper Cosmic 18.10 packages for latest releases within major series, see

- https://launchpad.net/~hvr/+archive/ubuntu/ghc/+packages?field.name_filter=&field.status_filter=published&field.series_filter=cosmic

let me know if this works for you.
