### ISSUE TITLE
doctest phase is broken with ghc >= 8.0 && <8.4

### ISSUE THREAD

**Issue by peti** [haskell-CI/haskell-ci#192]
See https://travis-ci.org/peti/hopenssl/builds/460740372 for an example. It appears that the builds with ghc >= 8.0 && <8.4 don't produce `ghc.environment.x86_64-linux-x.y.z` files any more, so `doctest` doesn't have a proper environment in which to run. It seems to me like this issue started occurring after the update to `cabal-install 2.4.1.0`.

**Comment by phadej** [comment]
@peti should be fixed in `master` with https://github.com/haskell-CI/haskell-ci/commit/cfce391609a3e96e13f21f7aa45e5941bedd17e1

Could you verify?

**Comment by peti** [comment]
Yes, the new code succeeds fine: https://travis-ci.org/peti/hopenssl/builds/460789031.
