### ISSUE TITLE
ghc/ghc-pkg version mismatch when using HEAD and -w

### ISSUE THREAD

**Issue by quasicomputational** [haskell-CI/haskell-ci#196]
This Travis configuration doesn't work, despite looking reasonable:

```
language: haskell
cabal: head
ghc: head
script:
  - cabal new-update
  - cabal new-build all --only-dependencies -w ghc-head
```

It fails with [this error](https://travis-ci.org/quasicomputational/travis-haskell-ghc-head/jobs/467016261):

```
$ cabal new-build all --only-dependencies -w ghc-head
cabal: Version mismatch between ghc and ghc-pkg: /opt/ghc/bin/ghc-head is
version 8.7.20181015 /opt/ghc/bin/ghc-pkg is version 8.0.2
```

In [quasicomputational/travis-haskell-ghc-head](https://github.com/quasicomputational/travis-haskell-ghc-head), I've got a slightly fuller worked example, with [a Travis build that fails](https://travis-ci.org/quasicomputational/travis-haskell-ghc-head/builds/467016259) and two that succeed despite looking very similar: `-w ghc-8.6.3` plus `ghc: 8.6.3` works fine, and omitting the `-w` altogether also works fine on `ghc: head`.

This could also turn out to be a cabal-install bug or the fault of the integrators at Travis, or I could even turn out to be holding it wrong. I am filing it here because my first thought was that this is some kind of packaging mishap, but that's a very rebuttable presumption.

**Comment by phadej** [comment]
This repository isn't about "Official" Haskell support on Travis. I remember discussions about that somewhere, but cannot find any pointers right now. Maybe @hvr remembers?

**Comment by quasicomputational** [comment]
Yes, hence the caveat at the end. I think it's suspicious that `-w ghc-8.6.3` works but `-w ghc-head` doesn't, which to me suggests packaging mistake or cabal-install bug rather than a problem with the Travis integration.

**Comment by phadej** [comment]
It's not a proper bug in `cabal-install`; neither the packaging of GHC. The way `cabal-install` deduces the name of `ghc-pkg` from a compiler name given via `-w`/`--with-compiler` doesn't cover all the possible cases. (probably it's left to strip the version at the end, but not recognise anything fancier, I'm not sure, maybe there are comments in the code).

Herbert's `ghc-head` package have also e.g. `ghc-8.7` links which work, but require some scripting (or updating once in a while when head's version changes).

I think it works by accidental with `haskell-ci` as we have only single ghc installed.

**Comment by quasicomputational** [comment]
Makes sense. Thanks for clearing it up!

I'd definitely consider it a deficiency in cabal-install, since it has all the information it needs to guess at a correct `ghc-pkg` command. I'll open up an issue over there as an aspirational TODO.
