### ISSUE TITLE
Former switch flags now require explicit BOOL arguments

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#214]
While using the latest `haskell-ci` HEAD, I was surprised to discover that my existing `.travis.yml` configurations no longer work due to a change in `--ghc-head`'s behavior:

```
$ haskell-ci cabal.project --ghc-head
The option `--ghc-head` expects an argument.
```

This is odd, since `--ghc-head` (without an argument) used to work just fine previously. It wasn't until I consulted `--help` that I realized what it's doing now:

```
  --ghc-head BOOL          Build also with ghc-head
```

Having to pass `--ghc-head true` or `--ghc-head false` explicitly seems like strange UI design, since most CLI parsers for boolean-valued options would just treat the presence of `--ghc-head` as "true", and its absence as "false". (In other words, the behavior of `switch` from `optparse-applicative`.)

Is there a particular reason why this convention was changed? And can it be changed back?

**Comment by phadej** [comment]
For ghc-head yes, for others see comment in other issue: i plan to make flags accept version ranges. (And there are also limitations of what kind of cli UI is encodable with optparse-applicative)

**Comment by RyanGlScott** [comment]
> For ghc-head yes, for others see comment in other issue: i plan to make flags accept version ranges.

Even if these flags accept version ranges, having to explicitly pass a bool seems strange. I would expect the representable states to be:

* `--flag` (enable flag, with default range)
* `--flag=RANGE` (enable flag, with specified range)
* Flag is absent (disable flag)

Having to explicitly pass `--flag=true` feels redundant.

> (And there are also limitations of what kind of cli UI is encodable with optparse-applicative)

To be clear, I'm not suggesting that you literally use the `optparse-applicative` library to accomplish this, only that you tweak the UI to match the presentation of how `optparse-applicative` would treat switch flags.

**Comment by phadej** [comment]
`optparse-applicative` doesn't support (AFAIK) optional arguments, but I agree that explicit boolean is ugly. I'll think about how to make this ok-ish.

**Comment by phadej** [comment]
Maybe I'll do `--haddock`, `--no-haddock` and `--haddock-jobs` flag zoo.

For now, closing as current issue is resolved.
