### ISSUE TITLE
Release to Hackage

### ISSUE THREAD

**Issue by chris-martin** [haskell-CI/haskell-ci#224]
It's been a while since this project has had a release on Hackage; in particular I'm sorely missing the fix for #180, and it's a lot easier to install things if they're in the package repo.

**Comment by phadej** [comment]
I honestly don't know what's @hvr idea for release strategy.

FWIW, I think that I did most things I wanted in this small "sprint", and I don't have any changes in the pipeline. That means, that we could make new release.

**Comment by hvr** [comment]
@phadej sure, go for it :-)

**Comment by chris-martin** [comment]
Is there anything I can do to help this along?

**Comment by phadej** [comment]
https://hackage.haskell.org/package/haskell-ci-0.2
