### ISSUE TITLE
A middle ground between --tests and --no-tests

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#236]
Currently, `haskell-ci` gives you the ability to prevent building any test suites using the `--no-tests` flag. This is _almost_ what I need, but not quite. I have a project where I can't run the test suites on Travis due to the tests' [reliance on a web browser](https://github.com/ku-fpg/blank-canvas/issues/73) being run at the same time. That being said, I still want to _build_ (but not run) the test suite on Travis so as to ensure that the code doesn't bitrot. Unfortunately, `--no-tests` is too heavy-handed, as it prevents the test suites from being built in the first place.

Could there be a flag that permits the test suite to be built but not run, similarly to how benchmarks are currently handled? I'm not sure what the best name for this flag should be, or if it would make sense to make `--no-tests` further configurable to allow this.

**Comment by phadej** [comment]
I was thinking of introducing `--run-tests`, `--no-run-tests` `--run-tests-job=RANGE` configuration, which is
- intersected with `--tests`
- says when to run tests.

**Comment by RyanGlScott** [comment]
Sounds good to me! If these flags do intersect with `--tests`, it would be good to document somewhere how that works, but otherwise I don't foresee any complications.

**Comment by phadej** [comment]
Intersection means hopefully obvious: only built tests can be run, but you can run tests on less jobs. E.g.

```
haskell-ci --tests-jobs '>= 7.6' --run-tests-jobs '>=8.0' ...
```

**Comment by phadej** [comment]
... and with

```
haskell-ci --no-tests --run-tests
```

you won't build (and run) any tests.

**Comment by phadej** [comment]
`--run-tests` is there
