### ISSUE TITLE
Allow specifying patch files

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#257]
99% of the time, `haskell-ci` will just work for your project out of the box. The remaining 1% of your projects, however, often require a handful of manual tweaks in order to make everything work just right. An example of this can be found in the `base-compat` library, which adds some additional goodies to `haskell-ci`'s autogenerated `.travis.yml` file in the form of [this patch](https://github.com/haskell-compat/base-compat/blob/257e6971d5d69720388f6cad5eac58c937176a48/travis.yml.patch).

To make this process a little more streamlined, it would be convenient if `haskell-ci` could automatically apply these patch files as a part of its `.travis.yml` generation process. Of course, there is potential for fragility here, since it's possible that a patch file created at one point in time will no longer apply with a later version of `.travis.yml`, but this would at the very least substantially simplify the process of actually _using_ the patch in the event that one has to tweak the original, unpatched `.travis.yml` file.

**Comment by RyanGlScott** [comment]
I started implementing `--patch` the other day and realized there's something not quite fully baked about this idea. Namely, what happens if you're simply dumping the generated Travis YAML file to stdout? The `patch` utility assumes that the thing that you're patching is contained in some file, but if you're just dumping YAML to stdout, then that assumption won't hold.

I can see two ways to answer this question:

1. Make `--patch` only work if you also specify the `--output` flag (so that there is always a file to patch).
2. Instead of shelling out to `patch`, find some Haskell program that implements the same logic as `patch` (but which can work over `String`s instead of just files). I'm not aware of such a Haskell program off the top of my head, however.

**Comment by phadej** [comment]
Option two would be nice.

Yet option 1. can be done in temporary directory. In fact, i’d require to do it so.

Have to check that currently we never overwrite output when there’s an error
