### ISSUE TITLE
Preserve contents after # EOF when regenerating

### ISSUE THREAD

**Issue by maoe** [haskell-CI/haskell-ci#260]
Currently any custom configurations in .travis.yml are overridden when running `haskell-ci regenerate`. It would be great if it could preserve any additional contents after `# EOF` for example.

**Comment by phadej** [comment]
My current opinion is wontfix. Ryan proposes supporting `patch` which would be more flexible, and solves similar problem.

Yet in general, i’d rather teach `haskell-ci` to generate needed bits.

**Comment by maoe** [comment]
> My current opinion is wontfix. Ryan proposes supporting `patch` which would be more flexible, and solves similar problem.

Ah I wasn't aware of #257. It looks great. I have a project that requires to apply a patch in `before_install` section. I'm fine to close this ticket in favor of it.

> Yet in general, i’d rather teach `haskell-ci` to generate needed bits.

I'm not sure if it's a good idea to _generate_ every needed bit. For example `deploy` section can have too much info to pass as command line arguments. I think it's more ergonomic to use a patch (as in #257) or a template (as in this ticket).

**Comment by phadej** [comment]
I'm open to include `deploy` section as is in `cabal.haskell-ci` configuration file, everything doesn't need to be command line arguments. Or if there's just a lot of arguments, then the configuration file is a good place to have, instead of 1D command line spell you'll have 2D configuration file :)

**Comment by phadej** [comment]
Note: I'm eager to accumulate what kind of needs people have, as there's hardly a feature in `haskell-ci` which is used only by a single package. For example Ryan's `base-compat` need is not so unique: install an extra tool, run it. So maybe allowing extra (shell) steps to be appended to `install` and `script` parts would make sense: general and flexible, not still not completely arbitrary `patch`.

**Comment by phadej** [comment]
There's `--patches` now. Does it solve your problem?

**Comment by maoe** [comment]
I'll give it a try.

**Comment by maoe** [comment]
Just trying it in https://github.com/maoe/influxdb-haskell/tree/feature/ghc-8.8 with haskell-ci from current master.

`haskell-ci travis influxdb.cabal --ghc-head --travis-patches .travis/influxdb.patch` seems to work but regenerate fails for some reason:
```
% haskell-ci regenerate                                                                                 1 ↵ ✭
Invalid argument `influxdb.cabal'

Usage: haskell-ci CABAL.FILE ([-o|--output FILE] | [--stdout])
                  [--config CONFIGFILE] ([--cabal-install-version VERSION] |
                  [--jobs JOBS] | [--jobs-selection uniform|any] |
                  [--copy-fields none|some|all] | [--local-ghc-options OPTS] |
                  [--cache] | [--no-cache] | [--install-dependencies] |
                  [--no-install-dependencies] | [--installed +/-PKG] | [--tests]
                  | [--no-tests] | [--tests-jobs RANGE] | [--run-tests] |
                  [--no-run-tests] | [--run-tests-jobs RANGE] | [--benchmarks] |
                  [--no-benchmarks] | [--benchmarks-jobs RANGE] | [--haddock] |
                  [--no-haddock] | [--haddock-jobs RANGE] |
                  [--no-tests-no-benchmarks] | [--no-no-tests-no-benchmarks] |
                  [--no-tests-no-benchmarks-jobs RANGE] | [--unconstrained] |
                  [--no-unconstrained] | [--unconstrained-jobs RANGE] |
                  [--cabal-check] | [--no-cabal-check] | [--branches BRANCH] |
                  [--irc-channels IRC] | [--project-name NAME] | [--folds FOLD]
                  | [--ghc-head] | [--no-ghc-head] | [--postgresql] |
                  [--no-postgresql] | [--env ENV] | [--allow-failures JOB] |
                  [--last-in-series] | [--no-last-in-series] | [--osx JOB] |
                  [--apt PKG] | [--travis-patches PATCH] | [--doctest] |
                  [--no-doctest] | [--doctest-jobs RANGE] |
                  [--doctest-options OPTS] | [--doctest-version RANGE] |
                  [--doctest-filter-packages PKGS] | [--hlint] | [--no-hlint] |
                  [--hlint-job JOB] | [--hlint-yaml PATH] |
                  [--hlint-options OPTS] | [--hlint-version RANGE])
```

**Comment by maoe** [comment]
The issue I wrote above were due to a change in command line interface. Removing travis should fix it.

I've been using the travis-patchs option successfully. Closing.
