### ISSUE TITLE
`regenerate` should work with `-o`

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#264]
Currently, the `regenerate` command makes the assumption that it should look for `REGENDATA` from a file named `.travis.yml`, even if you say otherwise:

```
$ haskell-ci regenerate -o cabal.project.messy.travis.yml 
haskell-ci: .travis.yml: openFile: does not exist (No such file or directory)
```

Shouldn't it look in `cabal.project.messy.travis.yml` instead?

My concrete use case is testing particular YAML files in `haskell-ci`'s `fixtures` directory, which are not named `.travis.yml`.

**Comment by phadej** [comment]
Did we fix this?

**Comment by RyanGlScott** [comment]
As far as my needs are concerned, this is indeed fixed. You mentioned in https://github.com/haskell-CI/haskell-ci/pull/265#issuecomment-484268211 that you might want to do some additional refactoring, so I didn't want to close the issue just yet in case you were using this issue as a reminder to do the refactoring later.

**Comment by phadej** [comment]
I forgot what I wanted to do, maybe I did. :) Closing.

**Comment by phadej** [comment]
(Ah, now I remember, moving to `paths`, it's WIP, but not urgent).
