### ISSUE TITLE
8.6.5 support for Disco Dingo?

### ISSUE THREAD

**Issue by jrp2014** [haskell-CI/haskell-ci#266]
It would be great to provide this.  (I don't expect any differences other than package metadata from cosmic versions.)

**Comment by hvr** [comment]
Ok, so we now enter a short phase of having to support 3 LTS, and 2 non-LTS releases (see https://wiki.ubuntu.com/Releases) as those are the currently non-EOL'ed ones :-)

**Comment by phadej** [comment]
For people not familiar with codenames of Ubuntu releases, I save you a click:
*Ubuntu 19.04 (Disco Dingo)*

**Comment by phadej** [comment]
@hvr IMHO you could procrastinate so 14.04 would drop in a week :) (April 2019 is EOL of 14.04 trusty)

**Comment by phadej** [comment]
14.04 EOL'd, isn't it?

**Comment by hvr** [comment]
I've been able to resolve the quota issues and there's now Disco built packages, see https://launchpad.net/~hvr/+archive/ubuntu/ghc/+packages?field.name_filter=&field.status_filter=published&field.series_filter=disco
