### ISSUE TITLE
.travis.yml fails for unix's CI on GHC 7.8.1 and 7.8.2 only

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#267]
This is an unusually specific bug report, but I do think that it reveals a lurking bug in `haskell-ci`. The immediate issue is that after updating `unix`'s `haskell-ci`–generated `.travis.yml` file to use version `0.3.20190425`, the builds for GHC 7.8.1 and 7.8.2 [started to fail](https://travis-ci.org/haskell/unix/builds/525532625) all of a sudden. Here is the relevant excerpt from the [GHC 7.8.2 log](https://travis-ci.org/haskell/unix/jobs/525532644):

```
$ for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(unix)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done
The command "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(unix)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done" failed and exited with 1 during .
```

I believe the reason that this command is throwing exit code 1 all of a sudden is because `haskell-ci` now uses `set -o pipefail`, so if one of the commands in that series of pipes fails, then the whole thing will fail as well. So why is GHC 7.8.2 failing here but not, say, GHC 7.8.3? Let's compare the output of `$HCPKG list --simple-output` to see why. On GHC 7.8.2, it's this:

```
$ /opt/ghc/7.8.2/bin/ghc-pkg list --simple-output
Cabal-1.18.1.3 array-0.5.0.0 base-4.7.0.0 bin-package-db-0.0.0.0 binary-0.7.1.0 bytestring-0.10.4.0 containers-0.5.5.1 deepseq-1.3.0.2 directory-1.2.1.0 filepath-1.3.0.2 ghc-7.8.2 ghc-prim-0.3.1.0 haskell2010-1.1.2.0 haskell98-2.0.0.3 hoopl-3.10.0.1 hpc-0.6.0.1 integer-gmp-0.5.1.0 old-locale-1.0.0.6 old-time-1.1.0.2 pretty-1.1.1.1 process-1.2.0.0 rts-1.0 template-haskell-2.9.0.0 time-1.4.2 transformers-0.3.0.0 unix-2.7.0.1
```

But on GHC 7.8.3, it's this:

```
$ /opt/ghc/7.8.3/bin/ghc-pkg list --simple-output
Cabal-1.18.1.3 array-0.5.0.0 base-4.7.0.1 bin-package-db-0.0.0.0 binary-0.7.1.0 bytestring-0.10.4.0 containers-0.5.5.1 deepseq-1.3.0.2 directory-1.2.1.0 filepath-1.3.0.2 ghc-7.8.3 ghc-prim-0.3.1.0 haskeline-0.7.1.2 haskell2010-1.1.2.0 haskell98-2.0.0.3 hoopl-3.10.0.1 hpc-0.6.0.1 integer-gmp-0.5.1.0 old-locale-1.0.0.6 old-time-1.1.0.2 pretty-1.1.1.1 process-1.2.0.0 rts-1.0 template-haskell-2.9.0.0 terminfo-0.4.0.0 time-1.4.2 transformers-0.3.0.0 unix-2.7.0.1 xhtml-3000.2.1
```

What's unique about GHC 7.8.2 is that `unix` is the _last_ entry in the output. It appears no other versions of GHC besides 7.8.2 or 7.8.3 have this property, for whatever reason.

Unfortunately, I think `unix`'s position as the last entry in the output is exactly what is causing this whole command to throw exit code 1. That's because when `grep -vE -- '^(unix)$'` returns exit code 1 when `unix-2.7.0.1`, and `set -o pipefail` causes that exit code to be propagated through to the end. I'm unclear on the exact semantics of `bash` `for`-loops w.r.t. to exit codes, but it seems like a `for`-loop will return the exit code of its last iteration, which explains why this only happens when we `grep` for `unix-*` on the last iteration.

-----

Perhaps we should suppress `grep`'s exit code behavior to avoid this? Changing `grep -vE -- '^(unix)$'` to `(grep -vE -- '^(unix)$' || true)` seems to avoid this problem when I test it locally.

**Comment by phadej** [comment]
Please close if #268 fixes this

**Comment by RyanGlScott** [comment]
This fix has successfully been dogfooded in haskell/unix#129, so closing.
