### ISSUE TITLE
Should `tested-with` information be specified in `cabal.haskell-ci` instead?

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#273]
Currently, `haskell-ci` infers all of the information it knows about which versions of GHC to test by reading the `tested-with` stanzas of `.cabal` files. This technically works, although I find it a bit clunky for the following reasons:

1. If your repo has a `cabal.project` file with multiple `.cabal` files, `haskell-ci` requires that you list the exact same set of GHC versions in each `.cabal` file's `tested-with` stanza. This leads to a lot of ugly code duplication, such as in [here](https://github.com/ekmett/lens/blob/cd0e5f427b5d333b4ebe58e9104c3ad82746c982/lens.cabal#L15-L23), [here](https://github.com/ekmett/lens/blob/cd0e5f427b5d333b4ebe58e9104c3ad82746c982/examples/lens-examples.cabal#L19-L27), and [here](https://github.com/ekmett/lens/blob/cd0e5f427b5d333b4ebe58e9104c3ad82746c982/lens-properties/lens-properties.cabal#L16-L24).
2. Moreover, it's somewhat dubious to require that every `.cabal` file in a repo list the exact same versions of GHC in its `tested-with` stanza in the first place.

   As one example of an awkward tension that this creates, in the `primitive` repo I have to put [this list of GHC versions](https://github.com/haskell/primitive/blob/e0ff793a267f1004bb0c36590541ab58dba5168b/bench/primitive-benchmarks.cabal#L17-L25) (supporting all the way back to GHC 7.4.2) in `primitive-benchmarks.cabal`'s `tested-with` stanza. This is a complete lie, however—the `primitive` benchmarks only support GHC 7.8 onwards, a fact that is not at all obvious unless you look closely at the `build-depends`.

In light of this, perhaps we should consider allowing the range of tested GHC versions to be specified directly in `cabal.haskell-ci`? This would certainly be a change of convention for `haskell-ci`, but I think the payoff would be worth it.

**Comment by phadej** [comment]
For 2. point (and partly 1.)

https://github.com/haskell-CI/haskell-ci/blob/master/src/HaskellCI/Config.hs#L143-L144

## an example:

### .travis.yml

https://github.com/phadej/cabal-doctest/blob/master/.travis.yml#L164

### one package

https://github.com/phadej/cabal-doctest/blob/master/cabal-doctest.cabal#L23-L33

### another package in the same project

https://github.com/phadej/cabal-doctest/blob/master/simple-example/simple-example.cabal#L17

**Comment by RyanGlScott** [comment]
Interesting. I'm still very unclear on what `jobs-selection` actually _does_ from its `--help` description, however. Does `--jobs-selection=any` simply drop the requirement that all `.cabal` files in the same repo have the same range of GHC versions in their `tested-with` stanzas? Or is it more involved than that?

I'm assuming the `--jobs-selection=uniform` is the default value and explains the current behavior that I'm witnessing?

**Comment by phadej** [comment]
Yes, and yes. `uniform` is the default. `any` kind of takes an union, and only includes packages with matching `tested-with` in particular jobs `cabal.project`, the `tested-with` sets could be completely disjoint. (There is a TODO do print INFOs on how packages are included per job in that scenario).

My English isn't that good (as you have noticed ;), every documenttion improvement PR is very welcome.

I also feel that `--help` is too restricted to properly explain every bits and options. But writing proper manual is beyond me.

**Comment by RyanGlScott** [comment]
Good to know, thanks. In that case, I think `--job-selection=any` is what I really want.

I agree that `--help` isn't the best place to explain this nuance of `--job-selection`. I noticed that this repo's `cabal.haskell-ci` file (which I consider to be the _de facto_ users' guide for `haskell-ci`) doesn't make a mention of `job-selection` at all, so I think I would consider this issue resolved if this were documented there. Patch incoming.

**Comment by phadej** [comment]
I noticed that `--ghc-head` and `--jobs-selection=any` interact poorly.

**Comment by phadej** [comment]
Will fix shortly while also resolving #272

**Comment by RyanGlScott** [comment]
Was https://github.com/haskell-CI/haskell-ci/issues/273#issuecomment-490973876 fixed in commit 357c7ca40a49d3282cc3bfe6cd99963d940c9519? (It's hard to tell, since the Travis build breaks on that commit.)

**Comment by phadej** [comment]
@RyanGlScott no,it wasn't.
