### ISSUE TITLE
Add a --no-color flag

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#276]
Due to an unfortunate interaction with `travis_wait`, I have to manually patch the `haskell-ci`–generated `.travis.yml` file for [`base-compat`](https://github.com/haskell-compat/base-compat/pull/62/commits/a41dfd66bfd226014494beaf5ff78085d5ca7b85) to avoid the use of `color_cabal_output`. Having the ability to toggle off the use of `color` in `haskell-ci` directly would make this process easier.

**Comment by phadej** [comment]
Hmm. I wonder if it’s unfortunate interaction between travis_wait (which is a hack as it IIRC spawns background process etc), and piping to color_cabal_output. Yet, using something like travis_wait is justified, so we need to support the non-time-out.
