### ISSUE TITLE
Add support for optional-packages

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#283]
I can't use `haskell-ci` in the [`gl`](https://github.com/ekmett/gl/tree/01cc40c1935e982ff32ce822fef26e1a387af5c2) repo at the moment because `haskell-ci` won't generate the necessary commands to build the `gl` subdirectory, which is listed as `optional-packages: gl` in the `cabal.project` file.

**Comment by phadej** [comment]
Why `gl` is `optional-package`?

**Comment by RyanGlScott** [comment]
No idea. I don't make the news, I just report it.

**Comment by phadej** [comment]
> Like `packages`, specifies a list of package locations containing local packages to be built. Unlike `packages`, if we glob for a package, it is permissible for the glob to match against zero packages. The intended use-case for `optional-packages` is to make it so that vendored packages can be automatically picked up if they are placed in a subdirectory, but not error if there aren’t any.

It seems, one should use `packages`, as `gl.cabal` is always there, isn't it? Even it's regenerated, it's still there (the old one).

**Comment by ekmett** [comment]
I intend to move to generating the gl.cabal file as well. It really should be generated now but I was being lazy.
