### ISSUE TITLE
Debian 10 support?

### ISSUE THREAD

**Issue by jrp2014** [haskell-CI/haskell-ci#287]
What are the plans for making current GHC versions available on the latest stable Debian?

**Comment by hvr** [comment]
@jrp2014 I've been a bit busy, but it's definitely on my radar as soon as the GHC 8.8.1/Cabal 3.0 release dance has completed

**Comment by hvr** [comment]
This has been addressed; the instructions at https://downloads.haskell.org/debian/  have been updated to include Debian 10
