### ISSUE TITLE
Why do osx runs always run brew update?

### ISSUE THREAD

**Issue by merijn** [haskell-CI/haskell-ci#295]
At the moment macOS run on Travis always run `brew update` before starting. This is rather slow as it spends about 10-15 minutes updating all sorts of packages most Haskell code doesn't need/depend, so all that time is wasted. There doesn't appear to be a toggle to disable this behaviour either. Is there a reason why it's done this way?

**Comment by phadej** [comment]
Python3

**Comment by merijn** [comment]
Just installing python3 doesn't seem like it'd require running `brew update`, wouldn't simply running `brew install python@3` be sufficient? Or is there some reason we need bleeding edge version of python 3?

**Comment by phadej** [comment]
I don’t know if `upgrade` is required (it is on clean machine, travis image is ”something”) This repository has osx job, so you could try removing it, to see whether it’s fine. Maybe travis image even has python3 installed nowadays...

**Comment by phadej** [comment]
Resolved in https://github.com/haskell-CI/haskell-ci/pull/320
