### ISSUE TITLE
Problem with working when running tests with GHCJS

### ISSUE THREAD

**Issue by Shimuuar** [haskell-CI/haskell-ci#308]
When refactoring tests for math-functions I run into following problem. Tests for GHC passed while tests for GHCJS could not read tables for expected values. 

I worked around problem by adding 
```
 - if $GHCJS ; then cd ${PKGDIR_math_functions}; fi
 - ... tests ...
 - if $GHCJS ; then cd ..; fi
```
So it seems to be related to working dir. It seems to work but proper fix would be nice

**Comment by phadej** [comment]
That's known limitation of `ghcjs-tests` flag (which is experimental), we don't change the directory, as in general (multi-package setups) it's hard to deduce where one should go.

Maybe it could change when there's only single package, as then it's unambiguous.

**Comment by phadej** [comment]
@Shimuuar I merged the https://github.com/haskell-CI/haskell-ci/pull/309, could you try with current master.

**Comment by Shimuuar** [comment]
I'll try. I tried to build `haskell-ci` few days ago but run into some problems with Cabal-3.0

**Comment by Shimuuar** [comment]
Yes. It works https://travis-ci.org/Shimuuar/math-functions/builds/586677095

Thanks!
