### ISSUE TITLE
Explore having a GitHub actions target 

### ISSUE THREAD

**Issue by cartazio** [haskell-CI/haskell-ci#310]
There def gonna be some experimenting and foundational work needed.  But for GitHub orgs like /Haskell, gh actions seems to offer many more concurrent builds afaict !

**Comment by phadej** [comment]
FWIW, if I'll implement support for some other CI platform, I'd probably do GitLab CI next. But, if someone want to do stuff, some ground work is already done.

**Comment by merijn** [comment]
I've been thinking about looking into this (I've gotten around to diving into the GitHub Actions part, but not yet at looking how to integrate it with Haskell-CI).

I think the way the GitHub Actions work is super amenable to Haskell-CI, since it's possible to generate workflows that depend on action definitions in another repo, so we could actually keep all/most of the actions inside the Haskell-CI repository, minimising the gunk in everyone's repos (and even potentially supporting upgrading people's existing workflow without rerunning Haskell-CI in their repo).

**Comment by phadej** [comment]
Without knowing better, I'm against referring back to this repository. That would require to keep things very stable, something I cannot sign to.

i.e. I'm not sold to the idea of "upgrading people's existing workflows without rerunning haskell-ci in their repo", there definitely should be some versioning.

**Comment by merijn** [comment]
> That would require to keep things very stable, something I cannot sign to.

Ah! But GitHub action can refer to specific git commits, git tags, and branches, so we wouldn't be required to keep everything stable, we'd just have to commit to keep one branch/tag stable

**Comment by merijn** [comment]
So we can, in fact, generate versioned workflow but also (opt-in?) generate workflows reffering to a stable tag/branch, then we can experiment with improvements and eventually move the stable workflow branch/tag to the newly tested stuff. We could similarly (default or opt-in) generate workflows pinned to specific Haskell-CI commits (or even inline them in the repo to be tested).

**Comment by hvr** [comment]
@merijn fwiw, I briefly experimented with GitHub actions, and it looks promising; but one major feature is missing: artifact caching (but my understanding is they were working on it)

However, if you're interested in exploring the git-repo style way I'm open to the idea of creating a new experimental git repo inside github.com/haskell-CI  as playground for the GitHub action-script to refer to

Fwiw, below's a minimal Workflow yaml file which I used for manual experiments (note also that the default build image uses my GHC PPA, but unfortunately it doesn't have *all* GHCs going back to GHC 7.0 preinstalled; so one might need additional `apt-get install ghc-$VER` invocations)

Another thing I haven't tried yet is figuring out whether @mistuke's chocolatey packages are available via `choco install` on Windows builds, and also how the situation is for OSX builds.

```
%YAML 1.1
---
name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ls -l /opt/ghc/
        export PATH=/opt/ghc/bin:$PATH
        cabal --version
        ghc --version
        cabal update -v3
        cabal v2-build -w ghc-8.6.5 all
```

**Comment by hvr** [comment]
I think I've mostly worked it out how to get it working for linux/windows/osx in a uniform way... 

@merjin Are you still interested in helping out? How strong is your JavaScript Fu? :-)

**Comment by andreasabel** [comment]
+1. Given the pricing changes (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), it seems like travis-ci will be less of an option in the future, so having a GitHub actions target would be really great! See also #411.

**Comment by ethercrow** [comment]
Please have a look at Mark Karpov's post on GitHub Actions and Haskell: https://markkarpov.com/post/github-actions-for-haskell-ci.html

An example would be bytestring's CI: https://github.com/haskell/bytestring/blob/master/.github/workflows/ci.yml. There's even a PR to have a virtualized FreeBSD-based CI in addition to the usual Linux, Windows and macOS: https://github.com/haskell/bytestring/pull/322

**Comment by phadej** [comment]
> +1. Given the pricing changes (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), it seems like travis-ci will be less of an option in the future, so having a GitHub actions target would be really great! See also #411.

PRs (and forks if needs so) are welcome. There been some work to factor codebase, so reusable parts are reusable (e.g. `cabal-install-parsers` as a primary example). I don't feel any urge to do anything. I'm sorry.

**Comment by RyanGlScott** [comment]
What would you expect the interface for a GitHub Actions target to look like? I ask since much of `haskell-ci`'s current design assumes the existence of Travis. Looking at the output of `--help` alone, there are two flags (`--travis-patches` and `--raw-travis`) that have "Travis" directly baked in, and there are also two subcommands (`travis` and `regenerate`) that either have "Travis" the name or whose description directly mentions Travis. It wouldn't surprise me if there were other flags/subcommands that implicitly assumed certain Travis conventions.

This is not to say that pursuing GitHub Actions isn't a worthwhile goal, but it is likely that `haskell-ci` will need to be redesigned slightly to accommodate different CI backends. I'm yet unclear on what a backend-agnostic version of `haskell-ci` would look like.

**Comment by phadej** [comment]
> haskell-ci will need to be redesigned slightly to accommodate different CI backends. 

It have been all the time moving into that direction. The idea of introducing `travis` subcommand (and not e.g. `generate`) was to make it clearer that `travis` will not always be the only target.

So github actions (or gitlab or ...) should be possible to add without removing travis target. Then `--travis-patches` just won't do anything. Surely there are some internal assumptions about Travis, but hopefully nothing non generalisable.

One suggestion I can make, is that don't try to reuse the travis shell code directly. I'd probably copy paste the good bits and then see later if something can be generalized there.

For example, I think it would be better to generate independent steps for different jobs. Travis forces us to have single `build` list, so we have to do different-jobs conditionals in bash etc. It would be clearer to unfold that for GitHub actions. Also having `steps` in GitHub actions would be nice. (And not single big one).

**Comment by RyanGlScott** [comment]
This appears to have been done (or at least, most of the work has been done) in #416. Should this be closed?

**Comment by sjakobi** [comment]
> This appears to have been done (or at least, most of the work has been done) in #416. Should this be closed?

Awesome! :) It would be nice if the README would contain a bit of documentation on the new target, or at least mention it.
