### ISSUE TITLE
Support for Ubuntu 19.10 (Eoan Ermine) in Ubuntu PPA

### ISSUE THREAD

**Issue by AlistairB** [haskell-CI/haskell-ci#319]
Can the newly released Ubuntu version be supported in https://launchpad.net/~hvr/+archive/ubuntu/ghc?

**Comment by hvr** [comment]
@AlistairB I'll look into this asap; in the meantime you can most likely use the 19.04's branch on Eoan until the 19.10 optimized builds are done

**Comment by hvr** [comment]
@AlistairB effective immediately, there's now packages built natively for Eoan the PPA for all GHC 7.0 through 8.8 and cabal-install 2.4,3.0,head

**Comment by AlistairB** [comment]
Thank you!
