### ISSUE TITLE
`haskell-ci regenerate` fails with ".travis.yml: openFile: resource busy (file is locked)" on 0.7.20191106

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#337]
To reproduce the issue, try to regenerate the `.travis.yml` file from [`log-domain`](https://github.com/ekmett/log-domain) like so:

```
$ git clone https://github.com/ekmett/log-domain
$ cd log-domain/
$ git reset --hard cb0dd8123169dc56b2aa2e5ad41743670024bd26
$ .../haskell-ci/dist-newstyle/build/x86_64-linux/ghc-8.8.1/haskell-ci-0.7.20191106/x/haskell-ci/build/haskell-ci/haskell-ci --version
$ .../haskell-ci/dist-newstyle/build/x86_64-linux/ghc-8.8.1/haskell-ci-0.7.20191106/x/haskell-ci/build/haskell-ci/haskell-ci regenerate
*INFO* Generating Travis-CI config for testing for GHC versions: ghc-head 8.0.2 8.2.2 8.4.4 8.6.5 8.8.1
haskell-ci: .travis.yml: openFile: resource busy (file is locked)
```

As far as I can tell this is a regression, since this does not occur if I use `haskell-ci-0.6`. Running `.../haskell-ci '--output=.travis.yml' '--config=cabal.haskell-ci' 'cabal.project'` manually works around the issue.

**Comment by phadej** [comment]
I cannot reproduce that, even if I modify `.travis.yml`. But I added a optimistic fix, can you try it?

**Comment by RyanGlScott** [comment]
That fixed the issue for me, thanks!
