### ISSUE TITLE
Add means to extend the build timeout

### ISSUE THREAD

**Issue by sgraf812** [haskell-CI/haskell-ci#350]
I have `unordered-containers` in the dependencies of the `hlint` build, which *always* runs into a timeout in CI: https://travis-ci.org/sgraf812/datafix/jobs/635182382

My workaround so far was to manually edit the generated Travis file to use `travis_wait 20` and remove `color_cabal_output` because it swallows the output of `travis_wait`:

```diff
diff --git a/.travis.yml b/.travis.yml
index 46bff6d..de5862c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -93,7 +93,7 @@ install:
   - rm -fv cabal.project cabal.project.local cabal.project.freeze
   - travis_retry ${CABAL} v2-update -v
   - ${CABAL} v2-install $WITHCOMPILER -j2 doctest --constraint='doctest ==0.16.*' | color_cabal_output
-  - if [ $HCNUMVER -ge 80800 ] ; then ${CABAL} v2-install $WITHCOMPILER -j2 hlint --constraint='hlint ==2.1.*' | color_cabal_output ; fi
+  - if [ $HCNUMVER -ge 80800 ] ; then travis_wait 30 ${CABAL} v2-install $WITHCOMPILER -j2 hlint --constraint='hlint ==2.1.*' ; fi
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
```

**Comment by phadej** [comment]
coloring is removed, and to install hlint there's `hlint-download-binary` which is on by default, so timeout shouldn't happen.

I see you use quite old version of `haskell-ci` too.

**Comment by sgraf812** [comment]
Alright! Yeah, I was using the one in stable nix's `nixos-19.09` channel, which is probably based on an old stackage LTS snapshot.

**Comment by phadej** [comment]
The `0.3.x` version you had was never released. Odd version numbers are development (only in this repository) version. I have *no idea* what is in `nixpkgs` if any.
