### ISSUE TITLE
OSX travis builds are broken due to Python 3

### ISSUE THREAD

**Issue by Mikolaj** [haskell-CI/haskell-ci#352]
E.g., here: https://travis-ci.org/LambdaHack/LambdaHack/jobs/637727414#L527

The only slightly related commit I can find is

https://github.com/haskell-CI/haskell-ci/commit/42497d66d24ceaca2fa6dced291e933cc2bbfbb8

so that's probably not fixed yet.

**Comment by Mikolaj** [comment]
BTW, removing Travis cache didn't help.

**Comment by phadej** [comment]
It looks like you are using an ancient version of haskell-ci to generate the script. Have you tried regenerating with more recent one?

**Comment by Mikolaj** [comment]
I've re-hacked the Travis code with snippets from the new generation script, it broke everything and then, everything works. Thank you. :)
