### ISSUE TITLE
Profiled (base) libraries for Ubuntu?

### ISSUE THREAD

**Issue by jrp2014** [haskell-CI/haskell-ci#354]
The pvrs for Ubuntu are a great resource.  Is there an easy way to get the profiled libraries included, too.

I seem to just be `Perhaps you haven't installed the profiling libraries for package ‘base-4.13.0.0’?` when I try to profile my projects.

**Comment by sjakobi** [comment]
@jrp2014 Did you install `ghc-8.8.2-prof`?

**Comment by jrp2014** [comment]
Ah. I hadn’t spotted that that existed!
