### ISSUE TITLE
Doesn't work for multi-package setup with inter-dependencies

### ISSUE THREAD

**Issue by feuerbach** [haskell-CI/haskell-ci#361]
First of all, thanks for making this. I'm migrating from the ["complex" stack setup](https://docs.haskellstack.org/en/stable/travis_ci/) that I've been using for many years, and I find the ability to auto-generate .travis.yml very convenient, especially for smaller projects.

However, when setting this up for tasty, I ran into this issue after generating the config with `haskell-ci cabal.project --output .travis.yml` (using haskell-ci 0ebd7030064aa4c3500ebc85a3d20fc44cf6fe04):

```
$ ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all

cabal: Cannot select only the dependencies (as requested by the '--only-dependencies' flag), the package tasty-1.2.3 is required by a dependency of one of the other targets.
```

[Travis log](https://travis-ci.org/feuerbach/tasty/jobs/645021149)

FWIW, I've fixed this for myself simply by removing the `--dep` steps, as they don't seem necessary.

**Comment by phadej** [comment]
```
% haskell-ci --help|grep dep
                    --install-dependencies | --no-install-dependencies | 
  --no-install-dependencies
                           Skip separate dependency installation step
```
