### ISSUE TITLE
Turning off email notifications

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#369]
Is there a way to configure that email notifications should be turned off? In the `.travis.yml` it looks like this:

```
notifications:
  email: false
```

**Comment by phadej** [comment]
No, that should be easy enough to add.

Do you want to try yourself?

You need to 
- add a `Bool` field to `Config` type in `HaskellCI.Config`
   - tell the grammar in `configGrammar` (there are plenty boolean fields for an example).
   - other type directed fixes
- Edit `TravisNotifications` type in `HaskellCI.Travis.Yaml` to contain a field for emails
   - remember to generate related field in `ToYaml` instance
- Connect above in `HaskellCI.Travis`.

**Comment by sjakobi** [comment]
Many thanks for the fix @phadej. It works flawlessly! :)

**Comment by phadej** [comment]
turns out I needed it myself...
