### ISSUE TITLE
How to enable testing with GHC 8.10?

### ISSUE THREAD

**Issue by neongreen** [haskell-CI/haskell-ci#379]
I added `tested-with: GHC ==8.10.1`, but got `*ERROR* 'tested-with:' specifically refers to unknown 'GHC' versions: 8.10.1`.

What's the idiomatic way to generate a script that would test with GHC 8.10.1?

**Comment by phadej** [comment]
You have to use version in `master`. I'll try to make a release to Hackage soon, as all small issues have been resolved.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/haskell-ci-0.10 released

**Comment by emilypi** [comment]
@phadej ftw! Thank you!
