### ISSUE TITLE
Let me test with HEAD without modifying tested-with

### ISSUE THREAD

**Issue by neongreen** [haskell-CI/haskell-ci#39]
Currently I need to specify something like `GHC == 7.11.*` in `tested-with` so that the script would generate a `.travis.yml` file that tests with HEAD. It'd be nice if instead I could just give the script some command-line option (e.g. `--head`) that would mean “test with HEAD as well”.

**Comment by hvr** [comment]
The v2 script has a CLI parser, so this can be implemented now more easily

**Comment by ivan-m** [comment]
This seems to be available with `--ghc-head`.

**Comment by phadej** [comment]
@ivan-m thanks for pointing out. CLosing this
