### ISSUE TITLE
[Solution included] HCPKG seems to be set wrongly for osx

### ISSUE THREAD

**Issue by Mikolaj** [haskell-CI/haskell-ci#395]
Here:

https://travis-ci.org/github/LambdaHack/LambdaHack/jobs/693252187#L206

if fails with

/Users/travis/.travis/functions: line 109: /Users/travis/.ghc-pkg-install/ghc/bin/ghc-8.4.4: No such file or directory

The same for other GHCs.

**Comment by Mikolaj** [comment]
The line defining osx stuff should be change to the following and then it works fine:

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then HC=$HOME/.ghc-install/ghc/bin/$TRAVIS_COMPILER; WITHCOMPILER="-w $HC"; HCPKG=$HOME/.ghc-install/ghc/bin/${TRAVIS_COMPILER/ghc/ghc-pkg}; CABAL=$HOME/.ghc-install/ghc/bin/cabal; fi

**Comment by phadej** [comment]
https://hackage.haskell.org/package/haskell-ci-0.10.2

**Comment by Mikolaj** [comment]
Thank you!
