### ISSUE TITLE
GitHub Actions backend: Default to `on: push` when --branches is not set 

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#419]
If you use the GitHub Actions backend but fail to specify what branches to use with the `--branches` option, it will generate a YAML file without any `on:` information whatsoever. GitHub Actions is not happy with this and will throw this error ([example](https://github.com/goldfirere/singletons/actions/runs/421792426)):

```
No event triggers defined in `on`
```

`haskell-ci` should probably generate some sensible default for `on:` when `--branches` isn't set, such as [`on: push`](https://stackoverflow.com/a/63338112).

**Comment by phadej** [comment]
Does `on: push` builds pull requests from external repositories too? Should it be `on: [push, pull_request]`?

**Comment by RyanGlScott** [comment]
> Should it be `on: [push, pull_request]`?

Ah, I think you're right. (That'll teach me to blindly trust StackOverflow answers.)
