### ISSUE TITLE
[Fixed on master:] haskell-ci regenerate says: Invalid argument `FILE.cabal'

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#438]
```
$ haskell-ci regenerate
Invalid argument `agda2lagda.cabal'
```
This error message isn't comprehensible:
- I didn't pass such an argument
- I don't learn what the problem is and how to fix it

How do I use the `regenerate` command?
No extra help is offered when trying `haskell-ci regenerate --help`.
The generated `.travis.yml` contains these instructions:
```
# This Travis job script has been generated by a script via
#
#   haskell-ci 'travis' 'agda2lagda.cabal'
#
# To regenerate the script (for example after adjusting tested-with) run
#
#   haskell-ci regenerate
#
# For more information, see https://github.com/haskell-CI/haskell-ci
#
# version: 0.10.3
```

Note that the simple rerun of `haskell-ci` succeeds:
```
$ haskell-ci travis agda2lagda.cabal
*INFO* Generating Travis-CI config for testing for GHC versions: 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.2
```

I am using the latest release:
```
$ haskell-ci version-info
haskell-ci 0.10.3 with dependencies ...
```

Link to my repo: https://github.com/andreasabel/agda2lagda

Finally I checked the development version; the problem seems to be fixed there.  
```
$ haskell-ci version-info
haskell-ci 0.11.20201220

$ haskell-ci regenerate
No haskell-ci.sh, skipping bash regeneration
No .github/workflows/haskell-ci.yml, skipping GitHub config regeneration
*INFO* Generating Travis-CI config for testing for GHC versions: 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.2
```
So, maybe this is just a nudge to release...

**Comment by phadej** [comment]
Right now is a not a good moment to make a release, as GitHub actions support is very experimental, but once it is stabilised I'll make one.
