### ISSUE TITLE
GHA: --irc-if-in-origin-repo's parsing of GitHub URLs is fragile

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#440]
If I check out the `haskell-ci` repo at commit 8629a90db15ea453d65c6d20e94de75672fb41b4:

```
$ git clone https://github.com/haskell-CI/haskell-ci
$ git reset --hard 8629a90db15ea453d65c6d20e94de75672fb41b4
```

And then regenerate `.github/workflows/haskell-ci.yml`:

```
$ cabal run haskell-ci -- regenerate
```

Then the contents of `.github/workflows/haskell-ci.yml` will change!

```
$ git diff
diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
index 0979ac5..7629b83 100644
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -24,7 +24,6 @@ jobs:
     runs-on: ubuntu-18.04
     needs:
       - linux
-    if: ${{ github.repository == 'haskell-CI/haskell-ci' }}
     strategy:
       fail-fast: false
     steps:
```

It seems strange that this line in particular would be deleted, especially since `haskell-ci` enables the `irc-if-in-origin-repo` option. But things get even weirder from here. Let's try using a different URL and regenerating:

```
$ git remote set-url origin git@github.com:haskell-CI/haskell-ci.git
$ cabal run haskell-ci -- regenerate
```

All of a sudden, the deleted line is restored! That is, `git diff` will report no changes.

This appears to be because the logic that `haskell-ci` uses to parse `git` URLs assumes very particular conventions:

https://github.com/haskell-CI/haskell-ci/blob/8629a90db15ea453d65c6d20e94de75672fb41b4/src/HaskellCI/GitHub.hs#L564-L569

**Comment by RyanGlScott** [comment]
Another way this can occur is if `origin` is `git@github.com:haskell-CI/haskell-ci` instead of `git@github.com:haskell-CI/haskell-ci.git`.

**Comment by phadej** [comment]
I'll accept patches including `https` + making trailing `.git` optional.

That's why it's using `attoparsec` - the auto backtracking parsing combinator library :)

**Comment by RyanGlScott** [comment]
I was unclear on how far I should go with this, since there is a [dizzying variety of possible Git URLs](https://github.com/git/git/blob/6d3ef5b467eccd2769f1aa1c555d317d3c8dc707/t/t0110-urlmatch-normalization.sh). But perhaps we can get by with only a subset of these.

**Comment by phadej** [comment]
I think that supporting schemes which *Clone* button supports + https:// address is enough. Everything else people can add when they need that.

I'm really not motivated to track down what GitHub supports. Their documentation is far from complete, so I'd rather crowd-source that.
