### ISSUE TITLE
cabal-install-parsers does not pick up remote-repo field

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#459]
Synopsis: `cabal-install-parsers` does not pick up `remote-repo` field.

See https://github.com/haskell-hvr/cabal-plan/issues/70#issuecomment-754148692

According to https://cabal.readthedocs.io/en/latest/installing-packages.html#legacy-repositories :
> ```
>   remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive
> ```
> This is just syntactic sugar for
> ```
>   repository hackage.haskell.org
>     url: http://hackage.haskell.org/packages/archive
> ```
> although, in (and only in) the specific case of Hackage, the URL http://hackage.haskell.org/packages/archive will be silently translated to http://hackage.haskell.org/.

This is not implemented by https://github.com/haskell-CI/haskell-ci/blob/a4ea1ed56c7047619f755aeef8a39e35798ddc8e/cabal-install-parsers/src/Cabal/Config.hs#L119-L127
but maybe should, since users may have legacy `.cabal/config` files.

**Comment by phadej** [comment]
These legacy config files have to be very old (I haven't seen any new one written in five years).

**Comment by andreasabel** [comment]
I one started out with v1-cabal, it is not so unlike to have a config file from these times.  I am the constructive proof.
Old or not, a spec is a spec...
