### ISSUE TITLE
GHA silently ingores `--cabal-install-version`

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#470]
Passing `--cabal-install-version` to `haskell-ci github`, e.g.
```
haskell-ci github cabal.project --cabal-install-version 3.0
```
does not have seem to have any effect except for adding this to `REGENDATA`.

There should be a warning/error that this option is invalid for `github`.

**Comment by RyanGlScott** [comment]
I believe this is fixed as of #483.
