### ISSUE TITLE
Support ghc 8.10.3 on Debian

### ISSUE THREAD

**Issue by AlistairB** [haskell-CI/haskell-ci#471]
Just thought I'd create this for tracking. Some mention of this is in https://github.com/haskell/docker-haskell/issues/31

https://downloads.haskell.org/debian is only showing up to ghc 8.10.2

Happy to help if I can. Cheers :heart:

**Comment by AlistairB** [comment]
Missing versions are now there :tada:

**Comment by hvr** [comment]
Out of curiosity... how did you notice? I was too tired yesterday to followup and announce it yet... :-P

**Comment by AlistairB** [comment]
@hvr Haha, um obsessive checking ;) I just noticed after #474 was closed it all appeared in the ubunutu PPA, so I was keeping an eye on debian too.
