### ISSUE TITLE
cabal-install-parsers is out-of-date on Hackage

### ISSUE THREAD

**Issue by kozross** [haskell-CI/haskell-ci#492]
In master, this allows GHC 9, but on Hackage, it's not due to a bound on `base`. This is particularly odd in light of the Hackage release supporting Cabal 3.4. This is also causing innumerable transitive and direct blocks, including, but not limited to:

- [cabal-plan](https://github.com/haskell-hvr/cabal-plan/issues/72)
- [cabal-extras](https://github.com/phadej/cabal-extras/issues/78)
- [GHC 9 support in `text-ascii`](https://github.com/kozross/text-ascii/issues/18)

**Comment by phadej** [comment]
You can use `Cabal-3.4` library with GHC-8.10, there is nothing odd in that.

I don't understand why `text-ascii` is blocked on `cabal-bundler`? I don't see how that repository is using it?

**Comment by kozross** [comment]
I use it with `cabal-docspec`, which can't build with GHC 9, due to `cabal-bundler` not being able to build with GHC 9. This is breaking my CI for GHC 9.

**Comment by phadej** [comment]
Don't build `cabal-docspec`, download binary: https://github.com/phadej/cabal-extras/releases/tag/cabal-docspec-0.0.0.20210111

**Comment by kozross** [comment]
Does the binary run on all platforms? I'm CIing on Mac, Windows and Ubuntu.

**Comment by phadej** [comment]
Unfortunately no. I should setup CI to build it for all platforms, but hadn't got to it yet.
