### ISSUE TITLE
Support ShellCheck 0.7.2

### ISSUE THREAD

**Issue by sternenseemann** [haskell-CI/haskell-ci#507]
0.7.2 has been released, but haskell-ci won't support it. Any reason why the bound is so strict? PVP only permits non-breaking changes for a minor version bump.

**Comment by phadej** [comment]
ShellCheck adds new checks in minor versions, which may make `haskell-ci` fail. Therefore we have strict bounds.

**Comment by phadej** [comment]
Done in #510
