### ISSUE TITLE
github: `--test-output-direct` ignored, could become `--test-show-details=direct`

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#540]
The github backend currently ignores option `--test-output-direct`.  Feature request: pass this as option `--test-show-details=direct` to `cabal configure/build/test`.

**Comment by phadej** [comment]
Where? AFAIK it's on by default:

https://github.com/haskell-CI/haskell-ci/blob/master/.github/workflows/haskell-ci.yml#L262

and e.g.
![Screenshot from 2021-09-06 21-53-31](https://user-images.githubusercontent.com/51087/132254002-1543d4d7-afb9-4037-8d53-7e567e43294b.png)
in tests section of https://github.com/haskell-CI/haskell-ci/runs/3488306884

**Comment by andreasabel** [comment]
Ah, I was confused.  I passed `--test-output-direct` as additional argument to `haskell-ci github ...`, and the only thing that changed in `haskell-ci.yml` was the header comment with the `REGENDATA`.  So I thought it was ignored otherwise.
You are certainly right, `--test-show-details=direct` is anyway given to `cabal test`.
Sorry for the noise. :$

**Comment by andreasabel** [comment]
P.S.: Maybe to avoid confusion like mine, `--test-output-direct` could be filtered out so it does not end up in `REGENDATA` in the `github` instance.  Even better, a warning that this option is ignored...
