### ISSUE TITLE
Make `ghcup` the default setup method

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#542]
By default, `haskell-ci` uses `hvr-ppa`, but recent GHC versions are no longer provided there.  If you want these, you have to find out about the magic incantation like:
```
-- hvr-ppa latest are 9.0.1 and 8.10.4
ghcup-jobs: >= 9.2 || > 8.10.4 && < 9.0
```
How about making `ghcup` the default (which may internally also use `hvr-ppa`)?
This would make `haskell-ci github` work out-of-the-box.

(One could add a `hvr-ppa-jobs` field instead if insisting on this install method has broad support.)

**Comment by LeventErkok** [comment]
I think this can also help with #545, since it would unload the task of proper downloading of GHC to `ghcup` instead of using magic keys. (@andreasabel Correct me if I misunderstood!)

**Comment by andreasabel** [comment]
(@LeventErkok: I had to move away from Travis CI, as likely most of the community, so I now only care about the github backend of haskell-ci.)

**Comment by phadej** [comment]
`ghcup` is default method for GHC versions not in hvr-ppa
