### ISSUE TITLE
GitHub Actions backend doesn't respect `jobs`, resulting in lack of build parallelism

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#551]
In the `haskell-ci`–generated GitHub Actions workflow for `transformers-compat`, I noticed that despite settings `jobs: 2`, the dependencies were being built sequentially. On the other hand, this doesn't happen with the Travis backend:

https://github.com/haskell-CI/haskell-ci/blob/13af8162140c6437623a665962c3cbce3872c492/src/HaskellCI/Travis.hs#L193-L199

The GitHub Actions backend should do something similar.

**Comment by phadej** [comment]
looks like we didn't fix https://github.com/haskell-CI/haskell-ci/issues/421?

**Comment by RyanGlScott** [comment]
This is a slightly different issue. The `cabal.haskell-ci` file for `transformers-compat` specifies both of these options:

```
jobs:                   2
install-dependencies:   False
```

We explicitly pass `-j2` to `cabal build` when building the dependencies, but not to the subsequent invocation of `cabal build`. However, `transformers-compat` is a special case where libraries in its test suite depend on `transformers-compat` itself, so as a result, one can't build its dependencies beforehand (hence the use of `install-dependencies: False`). In order to recover some amount of package-level build parallelism, I'm using `jobs: 2`, which affects the subsequent invocation of `cabal build`.

**Comment by phadej** [comment]
It feels that we want to have granular jobs control for different steps. That is doable, but I won't have time to think about this now. Especially if this is only "bad" for `install-dependencies: False` setups.

**Comment by RyanGlScott** [comment]
In the meantime, would you accept a PR that makes the behavior of `jobs` consistent across both the Travis and GitHub Actions backends?

**Comment by phadej** [comment]
Btw, please comment on https://github.com/haskell/cabal/issues/6106 so `Cabal` folks could prioritize the issue. Whole `install-dependencies: False` is a workaround for it.

> In the meantime, would you accept a PR that makes the behavior of jobs consistent across both the Travis and GitHub Actions backends?

No, I won't have time to review it any time soon, I'm sorry.

**Comment by RyanGlScott** [comment]
> No, I won't have time to review it any time soon, I'm sorry.

I'm a little unclear. Are you philosophically opposed to the current design of the `jobs` flag, or are you just pressed for time? If it's the latter, I'd be happy to wait until you do have to review it (and I don't expect the patch to be that large).

**Comment by phadej** [comment]
> just pressed for time? 

That.

**Comment by RyanGlScott** [comment]
Sounds good. When you're ready, I've submitted a fix at #552.
