### ISSUE TITLE
Real-world examples are mostly outdated

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#562]
![image](https://user-images.githubusercontent.com/3664523/143854624-85244cfc-4d96-4ce8-9cc2-69a2ddcdb565.png)

* `lens` is a good example
* Does `Cabal` still use `haskell-ci`? I didn't find a config at first glance.
* `deepseq-generics` has a Travis config which seems pretty useless – the latest commit didn't even get CI.
* `filepath` links to https://github.com/ghc/packages-filepath, but the active repo is https://github.com/haskell/filepath, which doesn't seem to use `haskell-ci`.
* `arbtt` doesn't seem to use `haskell-ci`
* `circle-packing` has an ancient .travis.yml, but the repo seems pretty dead.

Are there other examples that might even showcase some advanced configurations?

* [`aeson`](https://github.com/haskell/aeson/blob/3dff21c7a0fec9a50f7ffd950a257368c7a6d25a/cabal.haskell-ci) seems good – it even  has some `constraint-set`s (#561).
* [`containers`](https://github.com/haskell/containers/blob/master/cabal.haskell-ci) showcases the `benchmarks` and `installed` fields.

Any other good examples?

**Comment by phadej** [comment]
"fixed" by https://github.com/haskell-CI/haskell-ci/commit/06a10a8c6e8bd24d3042246e3b5d78ee4f201d96
