### ISSUE TITLE
doctest version in generation script doesn't support GHC 9.2

### ISSUE THREAD

**Issue by raehik** [haskell-CI/haskell-ci#565]
I ran `haskell-ci generate` (installed from master) on [generic-lens](https://github.com/kcsongor/generic-lens), and the CI errored while installing doctest [log](https://github.com/raehik/generic-lens/runs/4402230274?check_suite_focus=true#step:11:1):

```
Run $CABAL --store-dir=$HOME/.haskell-ci-tools/store v2-install $ARG_COMPILER --ignore-project -j2 doctest --constraint='doctest ^>=0.17'
Resolving dependencies...
cabal-3.6.2.0: Could not resolve dependencies:
[__0] next goal: doctest (user goal)
[__0] rejecting: doctest-0.20.0, doctest-0.19.0, doctest-0.18.2, doctest-0.18.1, doctest-0.18 (constraint from command line flag requires ^>=0.17)
[__0] trying: doctest-0.17
[__1] next goal: ghc (dependency of doctest)
[__1] rejecting: ghc-9.2.1/installed-9.2.1 (conflict: doctest => ghc>=7.0 && <8.11)
[__1] skipping: ghc-9.2.1 (has the same characteristics that caused the previous version to fail: excluded by constraint '>=7.0 && <8.11' from 'doctest')
[__1] trying: ghc-8.10.2
[__2] next goal: base (dependency of doctest)
[__2] rejecting: base-4.16.0.0/installed-4.16.0.0 (conflict: ghc => base<0 && >=4.14 && <4.15)
...
```

Looks like doctest received GHC 9.2 on version 0.18.2. The version constraint is hardcoded in the GitHub CI workflow generation script - I changed my workflow to `^>=0.18.2` and it fixed the issue.

I'm not too sure what change to actually make here. Probably best to upgrade if doctest didn't drop any compiler support, but I haven't confirmed.

**Comment by sjakobi** [comment]
It's probably safe to change the constraint to `^>= 0.20.0`: https://matrix.hackage.haskell.org/#/package/doctest

**Comment by phadej** [comment]
Please make a PR. I'm not using `doctest` myself so I don't actively track its version. Or you can specify `doctest-version: ...` in the config.

**Comment by sjakobi** [comment]
How about simply removing the constraint on `doctest`?! That would reduce the maintenance burden.

**Comment by phadej** [comment]
You can specify `doctest-version: >=0.20` in your config too. I won't recommend that, as `doctest` may change in some major or minor ways (i remember I needed to adjust tests in the past when upgrading).

**Comment by raehik** [comment]
Thanks @sjakobi , I'll bookmark that site! I made the change, regenerated and ran the workflow, seems good. See the above PR.
