### ISSUE TITLE
hlint fails for GHC 9.0.1 in GHA

### ISSUE THREAD

**Issue by sternenseemann** [haskell-CI/haskell-ci#568]
```
Warning: Package db /github/home/.cabal/store/ghc-9.0.1/package.db does not
exist yet
HLint version 3.3.5
Downloading HLint version 3.3.5
Status Code: 404 Redirects: 0 Total time: 0.068589 Total Dsize: 9

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```

**Comment by phadej** [comment]
There is no binaries in 3.3.5 release: https://github.com/ndmitchell/hlint/releases/tag/v3.3.5 (compare with https://github.com/ndmitchell/hlint/releases/tag/v3.3.4), so this is an upstream issue.

**Comment by RyanGlScott** [comment]
I've opened ndmitchell/hlint#1338 upstream.

**Comment by RyanGlScott** [comment]
`hlint-3.3.6` [has been released](https://github.com/ndmitchell/hlint/releases/tag/v3.3.6) with corresponding bindists, so I believe this issue is fixed now.
