### ISSUE TITLE
Make unknown GHC version error a warning?

### ISSUE THREAD

**Issue by bgamari** [haskell-CI/haskell-ci#572]
Currently `haskell-ci` will throw an error if an unknown GHC version is found in `tested-with:`. Moreover, given the rate at which `haskell-ci` is released, the supported compiler list is, in my experience, usually out-of-date. Consequently, I think the status quo is doing more harm than good.

I can see a few possible approaches via which this could be improved

 * make this error rather manifest as a warning
 * rather make the whitelist a list of GHC major versions
 * introduce a flag allowing the user to ignore the error

**Comment by phadej** [comment]
So the problem is the rate on which haskell-ci is released. I don't feel it as I usually use the unreleased on Hackage `master` version.

With GHC-9.0.2 out and supported by GHC I'll just make a release now.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/haskell-ci-0.14 is on hackage.

**Comment by bgamari** [comment]
I suppose the question is what benefit we are gaining by being so selective in which GHC versions are accepted? To put it another way, how concretely does this check help the user?

**Comment by phadej** [comment]
Some internals are built around knowing which GHC versions exist. For example if user specifies `tested-with: GHC==9.0.*`. 

There is also a pedantic argument of at least trying to not use old `cabal-install`s with newer GHCs. It can easily be that users won't ever update the version of `cabal-install` used in CI if it would be allowed to just keep adding new (major) GHC versions if `haskell-ci` allowed that.

**Comment by phadej** [comment]
I like to error on pedantic side.

I'll reconsider this if e.g. ghcup metadata would be flagged stable and ok to be used by other tools.

**Comment by phadej** [comment]
Although I like how `haskell-ci` version pins exactly what is generated (we update `master` versions with a date), it's not affected by anything external at the moment.

I don't know. It's indeed not nice that `haskell-ci` needs to be recompiled to get new GHCs. On the other hand there was always some updates to the script generation in the meantime, so recompiling is usually good.
