### ISSUE TITLE
ShellCheck 0.8

### ISSUE THREAD

**Issue by felixonmars** [haskell-CI/haskell-ci#577]
haskell-ci currently has a strict bound on `ShellCheck ==0.7.2`. Any idea why this wasn't relaxed a bit?

Tested with ShellCheck 0.8 and it seems to build just fine. Sorry if I missed something.

**Comment by phadej** [comment]
Because `ShellCheck` added new checks in previous versions. While `haskell-ci` may compline, `ShellCheck` may complain of code `haskell-ci` generates.

**Comment by phadej** [comment]
DOne

**Comment by felixonmars** [comment]
Oops. Was planning to do it one day™ but I forgot. Thanks!
