### ISSUE TITLE
`list-ghc` includes version `8.0.1` but is not available on github actions

### ISSUE THREAD

**Issue by soenkehahn** [haskell-CI/haskell-ci#581]
`haskell-ci list-ghc` claims that `ghc-8.0.1` is a supported ghc version. But if I put `tested-with: GHC == 8.0.1` into a cabal file and do `haskell-ci github foo.cabal`, on github actions I get the following error:

```
E: Unable to locate package ghc-8.0.1
E: Couldn't find any package by glob 'ghc-8.0.1'
E: Couldn't find any package by regex 'ghc-8.0.1'
```

Should that version be removed from the output of `list-ghc`? Or does 'supported' not mean that it should work on github actions?

**Comment by andreasabel** [comment]
`ghcup` does not have `ghc-8.0.1`.  How is the generated `haskell-ci.yml` trying to install `ghc-8.0.1`?  Via `hvr-ppa`?
(Please provide more details.)

**Comment by phadej** [comment]
There isn't GHC-8.0.1 on hvr-ppa for Ubuntu Focal or [Bionic](https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=bionic). There is for [Xenial](https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=xenial)

Currently the list of GHC version is union of all available versions. We could track them better, per installation source though. (we have a workaround for `ghcup`), but I don't find that to have any priority.

**Comment by soenkehahn** [comment]
@andreasabel: The `haskell-ci.yml` says `setup-method: hvr-ppa`.

@phadej: Thanks for the reply. Maybe the wording of `list-ghc`'s output (it says `'Supported GHC versions:'`) should be changed to document this better. But your explanation makes sense, closing.
