### ISSUE TITLE
GHC downloads from HVR's PPA seem to stall

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#584]
Example: https://github.com/haskell-unordered-containers/unordered-containers/runs/6194563745?check_suite_focus=true

I'm working about this with `ghcup-jobs: True` (https://github.com/haskell-unordered-containers/unordered-containers/pull/442/commits/8aed0c04d3e7a1ad28083f9b3184177b352b18d9).

**Comment by phadej** [comment]
That error looks like a transient one. PPAs sometimes do that. Have it happend for a long time?

**Comment by sjakobi** [comment]
I was observing multiple similar failures for about 1.5 hours before I switched to `ghcup-jobs: True`.

**Comment by sjakobi** [comment]
Indeed downloads from the PPA seem to be working again. I'll probably stick with GHCup for all jobs though, since I'm already relying on it for recent GHC versions. One source of problems less!
