### ISSUE TITLE
Ci Action to regenerate CI action?

### ISSUE THREAD

**Issue by nomeata** [haskell-CI/haskell-ci#587]
I find I regenerate my CI actions very irregularly.

How about `haskell-ci` (optionally) also creates a CI job that
 * checks that the generated ci file is up-to-date (with regard to Tested-With in the .cabal file)
 * if it is not, pushes to the new CI file to that branch (so that a PR that extends the Tested-With range automatically tests the new compiler versions)
 * optionally does that with the latest released haskell-ci

**Comment by phadej** [comment]
I'm not a fan of automatic code commits. Feel free to implement a bot to do that.
