### ISSUE TITLE
Unable to locate package cabal-install-3.6

### ISSUE THREAD

**Issue by luntain** [haskell-CI/haskell-ci#596]
Build failed https://app.travis-ci.com/github/luntain/error-or-bundle/builds/252057583 with not being able to install `cabal-install-3.6`. It seems it is not there:

http://ppa.launchpad.net/hvr/ghc/ubuntu/pool/main/c/

Switching to `cabal-install-3.4` helped, but then it could not find `ghc-9.2.1`.

**Comment by phadej** [comment]
travis ci setup is not maintained, you are on your own.
