### ISSUE TITLE
Unreachable `if $HEADHACKAGE` statement in `apt` step?

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#597]
On [this `haskell-ci.yaml` file](https://github.com/haskell-compat/th-compat/blob/47f3531c72359012ddc72af107d066594f308671/.github/workflows/haskell-ci.yml), I see [this](https://github.com/haskell-compat/th-compat/blob/47f3531c72359012ddc72af107d066594f308671/.github/workflows/haskell-ci.yml#L116) in the `apt` step on line 116:

```yaml
            if $HEADHACKAGE; then "$HOME/.ghcup/bin/ghcup" config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml; fi
```

I'm not sure how it is possible for `HEADHACKAGE` to be defined on this line, however, as it is not declared until later, on [line 157](https://github.com/haskell-compat/th-compat/blob/47f3531c72359012ddc72af107d066594f308671/.github/workflows/haskell-ci.yml#L157) in the `Set PATH and environment variables` step:

```yaml
          if [ $((HCNUMVER >= 90400)) -ne 0 ] ; then echo "HEADHACKAGE=true" >> "$GITHUB_ENV" ; else echo "HEADHACKAGE=false" >> "$GITHUB_ENV" ; fi
```

As a result, I don't think the CI is ever reaching the `ghcup config add-release-channel` step. This doesn't seem to be breaking the build currently, but it is suspicious.

**Comment by phadej** [comment]
Somehow prereleases work nevertheless, as ghc-9.4.1 alpha is installed?

i think i'll fix this by simply unconditionally adding prerelease channel if *any* job needs it. AFAICT there shouldn't be harm in doing so. (but if you don't need prereleases, the script will stay a bit tidier)
