### ISSUE TITLE
Drop or takeover `ini`

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#601]
`haskell-ci` maybe one of the last users of `ini`, see: https://packdeps.haskellers.com/reverse/ini

On an attempt to add a CI to `ini`, see
- https://github.com/chrisdone/ini/pull/33

I got this [reply](https://github.com/chrisdone/ini/pull/33#issuecomment-1193378275) by @chrisdone:
> I’m not maintaining this package anymore. I’m going to archive it. Please feel encouraged to fork if desired!

followed by archival of the repo, muzzling further communication.

The problem, @chrisdone, is that a fork isn't sufficient because also rights on hackage are needed to publish fixes.
Atm the only maintainers are, see https://hackage.haskell.org/package/ini/maintainers/,
> [ChrisDone](https://hackage.haskell.org/user/ChrisDone)
> [joehillen](https://hackage.haskell.org/user/joehillen)

So, if you do not want to maintain `ini` anymore, please hand hackage maintainership over to me, `AndreasAbel`, at https://hackage.haskell.org/package/ini/maintainers/edit, so I can see what can be done about `ini` in the future.

**Comment by chrisdone** [comment]
Done!

**Comment by andreasabel** [comment]
I released https://hackage.haskell.org/package/ini-0.4.2
