### ISSUE TITLE
Generate a dependecy bump action?

### ISSUE THREAD

**Issue by nomeata** [haskell-CI/haskell-ci#610]
This may be out of scope for this project, but as it is called “haskell-ci”, maybe it isn’t.

Inspired by https://mobile.twitter.com/nomeata/status/1558859792919191552 I wonder if haskell-ci could generate a Github Action cron job that bumps dependencies automatically, at least in the common case. Something like

 * Figure out which of the current package’s dependencies are out of date.
 * Build and test with the newer versions (using `--allow-newer` and `--constraint`).
 * If successful, use a tool like [`cabal-bounds`](https://hackage.haskell.org/package/cabal-bounds) to update the .cabal file
 * If there are any changes to the cabal file, open a PR.
 * Bonus: Extract the changelog diff for the bumped dependencies and include in the PR.

Or maybe don’t even build and test, just open (or update) a PR that does the bumping, and do the testing as part of that PR.

Of course there are so many ways in which this can fail or be insufficient (one should test more combinations, it can fail because of missing dependencies, the maintainer still has to release manually, the test suite may not be good enough), but even something that helps in most cases would already be of great help.

Maybe a good HSoC project?

**Comment by domenkozar** [comment]
See also https://github.com/dependabot/dependabot-core/issues/2745

**Comment by phadej** [comment]
This is out of scope of `haskell-ci`.

**Comment by nomeata** [comment]
Would the following narrow building block be in scope here? (May require help on the Cabal side)

An option to test that the package can be builds with all dependencies constrained to the the highest version allowed by the cabal ranges?

Without this, a PR (maybe created by dependabot) that extends the dependency range of `foo` to allow new version 2 can still succeed because some other dependency `bar` still has `foo < 2`. If that PR is then merged and released, and later `bar` relaxes its dependency, suddenly user’s builds start failing.

**Comment by phadej** [comment]
`haskell-ci` generates CI config, it does one job well.

**Comment by nomeata** [comment]
Ah, that’s neat
```
-- Constraint sets
-- Package will be build with different constraints.
-- This is useful to check compatibility with older versions of dependencies.

constraint-set deepseq-1.4
  ghc: (>= 7.8 && <7.10) || == 8.2.2
  constraints: deepseq ==1.4.*
  constraints: binary installed
```
Indeed it’s great to test against old versions.

Not sure how practical it is to test against the latest allowed available version, as it duplicates the information from the `.cabal` file, and changes as Hackage changes. But with some help from Cabal maybe. I’ll take it [there](https://github.com/haskell/cabal/issues/8387) for now. Thanks!
