### ISSUE TITLE
idea: Use a container with preinstalled ghc

### ISSUE THREAD

**Issue by lf-** [haskell-CI/haskell-ci#619]
I'm debugging CI failures and impatiently waiting for apt installs to happen before I can see the actual failure. It would be great if those steps were built into a docker container so they are skipped :^)

(low priority issue)

**Comment by phadej** [comment]
The current approach doesn't require me to maintain anything "indefinitely", i.e. having containers for linux distribution x ghc version x cabal version x ....; or having *big* images with a lot of stuff in them.

For in-house product CI with small or/and opinionated user base using a container with preinstalled stuff is a great idea, but for `haskell-ci` use, I don't think it makes sense.

Test thoughtfully locally. The iteration speed will be much greater than any CI setup would give you.
