### ISSUE TITLE
Build failures with error "ERROR: '~hvr' user or team does not exist."

### ISSUE THREAD

**Issue by jhrcek** [haskell-CI/haskell-ci#621]
Hello,

I got a couple of build failures in https://github.com/jtdaugherty/brick/actions/runs/3101013142/jobs/5021918997 with error

```
Cannot add PPA: 'ppa:~hvr/ubuntu/ghc'.
ERROR: '~hvr' user or team does not exist.
Error: Process completed with exit code 1.
```
The ci config generated by recent version of haskell-ci is here: https://github.com/jtdaugherty/brick/blob/master/.github/workflows/haskell-ci.yml#L55-L74
It seems that failures affected all GHCs that have `setup-method: hvr-ppa`.

Could you please help me understand if there's something I can do to fix this?
Is there some potential issue with changing the setup-method to ghcup for all ghc versions?

**Comment by phadej** [comment]
I cannot reproduce. Could you restart the jobs, if it was a fluke in ppa setup?

**Comment by jhrcek** [comment]
Weird.
The same error occurred in 3 consecutive builds, every time in all 4 configurations using `setup-method: hvr-ppa`:
https://github.com/jtdaugherty/brick/compare/c527366347d828e811a9d1de19c9d60923469161...a117ff7790e1e753acc362530ff67e13e37707f7

But now I tried again in my fork and it works again.
Seems like some transient issue on some specific github runners :man_shrugging:
