### ISSUE TITLE
Should the default `distribution` be bumped from `bionic` to `focal` now?

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#628]
Should the default `distribution` be bumped from `bionic` to `focal` now?

I don't know what the policy is here, but `ubuntu-18.04` is discontinued as virtual environment by GHA now, and maybe that points to also upgrade here?

**Comment by phadej** [comment]
> I don't know what the policy is here, but ubuntu-18.04 

You are confusing the host environment and the docker image the CI is run in. The host is already `ubuntu-20.04`. The CI image can stay at 18.04 as long as it's still alive.

Using 20.04 CI would mean dropping support for GHC-7, as bindists are not available at hvr-ppa nor through ghcup for that and newer distributions. That's the reason to stay at 18.04 for as long as possible.

**Comment by andreasabel** [comment]
> You are confusing the host environment and the docker image the CI is run in.

Na, I didn't.

> Using 20.04 CI would mean dropping support for GHC-7, as bindists are not available at hvr-ppa

Well, I thought _20.04_ was the last version supported by hvr-ppa.  Turns out the story is more complicated:
- `focal` seems to have the major GHC version for 7.0 7.2 7.4 7.10, but misses 7.6 and 7.8: https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=focal
- `bionic` has all the latest GHC 7 major versions: https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=bionic
- `xenial` even has all the minor version: https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=xenial

> The CI image can stay at 18.04 as long as it's still alive.

I was worried that we would then test against old versions of the system libraries.  Packages break when confronted with newer system libraries, and the CI would be oblivious to that.  Isn't this a problem?

**Comment by phadej** [comment]
> Isn't this a problem?

I don't know which problem is worse. You can pick your devil. For me it's easier to stick to status quo.

**Comment by andreasabel** [comment]
Alright, fair enough.

I can easily workaround this by remembering to put `distribution: focal/jammy` into my `cabal.haskell-ci`.

**Comment by andreasabel** [comment]
@phadej wrote:
> Using 20.04 CI would mean dropping support for GHC-7, as bindists are not available at hvr-ppa nor through ghcup for that and newer distributions. That's the reason to stay at 18.04 for as long as possible.

Still possible.  
Though, let me document that now we are stuck with `actions/checkout@v3` because `v4` decided to move to `node20` which is not supported by `bionic` as it needs `glibc-2.28` but bionic has `2.27`.

Refs:
- https://github.com/actions/checkout/pull/1436
- https://github.com/agda/fix-whitespace/actions/runs/6078025441/job/16488643153 : `v4` fails on `bionic`
- https://repology.org/project/glibc/versions
