### ISSUE TITLE
nektos/act compatibility

### ISSUE THREAD

**Issue by ruby0b** [haskell-CI/haskell-ci#629]
It's nice to be able to test github CI locally without pushing to some remote.
https://github.com/nektos/act makes this possible but due to an issue with the `actions/cache` action haskell-ci won't work out of the box with it (https://github.com/nektos/act/issues/285).

The workaround is simply guarding the cache step using `if: ${{ !env.ACT }}` as mentioned in https://github.com/nektos/act/issues/285#issuecomment-987550101.
Including this would make act work without having to manually edit the CI file generated by haskell-ci and tracking down the workaround in the first place.

**Comment by phadej** [comment]
I'm not a fan. Why cannot `act` be taught to skip (or mock) `actions/cache` steps. That would solve issue for all.

**Comment by ruby0b** [comment]
Yeah that's fair, I agree.

For future reference:
1. I did find an act issue for fixing actions/cache: https://github.com/nektos/act/issues/989
2. That issue is not actually why the cache step fails in this case though. The caching should just not do anything and output a warning. The reason it fails is that act does not auto-install node when using `container:`. (See https://github.com/nektos/act/issues/973#issuecomment-1024328382) 

So for now you're probably best off adding `if: ${{ !env.ACT }}` to the cache action whenever you want to run act (and invoking `act -r` to reuse the container).
