### ISSUE TITLE
Support GHC 9.6 alpha?

### ISSUE THREAD

**Issue by andreasabel** [haskell-CI/haskell-ci#631]
@phadej: Are you intending to support GHC 9.6 alpha releases?

[I remember](https://github.com/haskell-hvr/regex-base/commit/26bb6c50435631b12c12123b3b5d45a30452fe16#diff-b99148ceaa20912d6a18034f0315f8b6a3c0b4699e9aa292fda1fd4892703de1 ) for e.g. 9.4.0.20220501 you supported such as `tested-with: GHC == 9.4.1`: 
I think this was a bit awkward.  It felt like `GHC == 9.4.0` would have been more appropriate.
I think the awkwardness was that the `GHC == 9.4.1` generated `haskell-ci.yml` broke after the release of GHC 9.4.1 because it would point to the alpha or RC still.  One had to rebuild `haskell-ci.yml` even though there was no change to `tested-with`.

**Comment by phadej** [comment]
Done in https://github.com/haskell-CI/haskell-ci/pull/632

**Comment by andreasabel** [comment]
> Done in #632

Thanks!

I see you used 9.6.1.  Maybe I didn't argue convincingly.  I do the 9.6.0 on my fork: https://github.com/andreasabel/haskell-ci/tree/ghc-9.6.0

**Comment by phadej** [comment]
> I think the awkwardness was that the GHC == 9.4.1 generated haskell-ci.yml broke after the release of GHC 9.4.1

Probably what broke in your case is that `haskell-ci` is not using `head.hackage` (and `allow-newer` for bundled libs) with proper release GHCs. I don't think there is a great solution to that problem. There is a period of time when GHC-x.y.1 is released but some CI may still need `head.hackage` (or at least `allow-newer`). I find it tiresome to toggle in CI config to use / not use `head.hackage`, so I just don't update CI builds until the dependencies are caught up.

One solution is to never toggle `head.hackage` automatically. That would come with another set of drawbacks.

**Comment by andreasabel** [comment]
I see.  Thanks for the explanation.  I guess this was the problem.
