### ISSUE TITLE
Please make Hackage release with latest compiler versions

### ISSUE THREAD

**Issue by maksbotan** [haskell-CI/haskell-ci#634]
Latest version on Hackage is 0.14.3, which supports only GHC 9.2.2. As far as I see, master branch supports 9.4.4 already. Can you please make a Hackage release with those?

Or are you planning something else for the next release besides compiler versions?

**Comment by phadej** [comment]
I'd prefer having an actual `cabal-install` which works (and 3.8.1.0 doesn't, see #606).

**Comment by maksbotan** [comment]
Thanks for the response!

CI logs are unavailable on that PR, by the way. What is the problem with cabal-install 3.8?

**Comment by phadej** [comment]
> What is the problem with cabal-install 3.8?

`cabal update` didn't work without `cabal.project`. And when got fixed it creates `dist-newstyle` directory. There haven't been bugfix releases, so I didn't check further.

**Comment by maksbotan** [comment]
Okay. Let's hope it'll get fixed.

**Comment by xsebek** [comment]
Hi @phadej, since you merged #635 can `haskell-ci` get a new release? :slightly_smiling_face:

It seemed to work fine for me to do `haskell-ci regenerate` after I installed it from sources.

**Comment by phadej** [comment]
@xsebek, no. `cabal-install-3.9.0.0` is not official release (it's a prerelease) and it's also broken in at least two ways which affects `haskell-ci`.

**Comment by ysangkok** [comment]
> it's also broken in at least two ways which affects haskell-ci.

Is cabal-install-3.10 also broken? I saw [a comment claiming that the --dry-run issue was fixed](https://github.com/haskell/cabal/issues/8706#issuecomment-1465160984). I suppose that was one of the two ways 3.9 was broken?

**Comment by phadej** [comment]
`cabal-install-3.10` prerelease had some issues, but all which were affecting `haskell-ci` are resolved in released version.

I update some other tools too and [`haskell-ci-0.16`](https://hackage.haskell.org/package/haskell-ci-0.16) is on Hackage.
