### ISSUE TITLE
Cache `$XDG_STATE_DIR/cabal/store` with `cabal-install-3.10`?

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#649]
From the [`cabal-install-3.10.1.0` release notes](https://github.com/haskell/cabal/blob/0ed12188525335ac9759dc957d49979ab09382a1/release-notes/Cabal-3.10.1.0.md#significant-changes):

> Cabal/cabal-install now uses the XDG Base Directory Specification to store configuration, caches, and the store.  Specifically, `$XDG_CONFIG_HOME/cabal` stores the configuration file, `$XDG_CACHE_HOME/cabal` stores downloaded packages and similar, and `$XDG_STATE_HOME/cabal` mainly contains the store of compiled packages.  Further, `cabal install` will put executables in `~/.local/bin` by default.

Now that `haskell-ci` is using `cabal-install-3.10.1.0`, should it be caching `$XDG_STATE_HOME/cabal/store`? (On my Linux machine, that is located at `~/.local/state/cabal/store`.)

**Comment by phadej** [comment]
No. haskell-ci writes its own `cabal/config`, specifically so that CI setup is not affected by `cabal-install` changing its defaults.

For example https://github.com/haskell-CI/haskell-ci/blob/3fc9d3c3fa01319c68491c584f65a8ac4d5b9698/.github/workflows/haskell-ci.yml#L114-L132

**Comment by RyanGlScott** [comment]
Ah, I overlooked that part! Thanks for the prompt reply.
