### ISSUE TITLE
Failure in `dump install plan`: `rejecting: Cabal-3.6.0.0/installed-3.6.0.0`.

### ISSUE THREAD

**Issue by kindaro** [haskell-CI/haskell-ci#677]
[Here is the workflow in question.](https://github.com/kindaro/cabal-prettify/actions/runs/6163166442)

My package depends on `Cabal`. It seems `haskell-ci` insists on a specific version of `Cabal`, namely 3.6.0.0, but my package needs 3.8 or newer.

**Comment by phadej** [comment]
Use `installed` configuration

```
  --installed +/-PKG       Specify 'constraint: ... installed' packages
```

Examples:
- https://github.com/haskell-CI/haskell-ci/blob/master/cabal.haskell-ci#L50-L52 
- https://github.com/haskell-hvr/cabal-plan/blob/b42d09e61d896c949403f2c05b7295d2e304ce6b/cabal.haskell-ci#L3

**Comment by kindaro** [comment]
Thank you Oleg @phadej. I generated the integration script anew by calling `haskell-ci` with the additional flags `--installed -Cabal` and my action is now green.

Is this stuff documented somewhere? I faintly recall solving a similar issue a while ago but I cannot recall any details. I have this link in browser history: <https://haskell-ci.readthedocs.io/en/latest/> — but it does not hold any actual documentation at this time.

**Comment by phadej** [comment]
`haskell-ci --help` and the `cabal.haskell-ci` in this repository (which serves as an example).
