### ISSUE TITLE
Use `ghcup-prereleases-0.0.8.yaml` (rather than `0.0.7`)

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#708]
In a recent attempt to use GHC 9.10.1-alpha1 in a `haskell-ci`–based CI job, it [fails with](https://github.com/glguy/th-abstraction/actions/runs/8316382452/job/22755785496#step:3:174):

```
Info: downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml as file /github/home/.ghcup/cache/ghcup-prereleases-0.0.7.yaml
Debug: Skipping and deleting etags file because destination file /github/home/.ghcup/cache/ghcup-prereleases-0.0.7.yaml doesn't exist
Debug: Status code was 200, overwriting
Debug: Parsed etag: "7aaf598e2ddbd3789b9aa31ad616080f21fabb39b52af77607f75d923f3d5ab0"
Debug: Writing etagsFile /github/home/.ghcup/cache/ghcup-prereleases-0.0.7.yaml.etags
Debug: Decoding yaml at: /github/home/.ghcup/cache/ghcup-prereleases-0.0.7.yaml
Warn: New GHCup version available: 0.1.22.0. To upgrade, run 'ghcup upgrade'
Error: []8;;[https://errors.haskell.org/messages/GHCup-00010\GHCup-00010]8;;\]](https://errors.haskell.org/messages/GHCup-00010%1B/GHCup-00010%1B]8;;%1B/]) Unable to find a download for 9.10.0.20240313
Error: Also check the logs in /github/home/.ghcup/logs
Error: Process completed with exit code 1.
```

I believe this may be the result of `haskell-ci` using [`ghcup-prereleases-0.0.7`](https://github.com/haskell/ghcup-metadata/blob/8b6dfe17264a7ac9d3bda97de4f41205c78e5f15/ghcup-prereleases-0.0.7.yaml) rather than the newer [`ghcup-prereleases-0.0.8`](https://github.com/haskell/ghcup-metadata/blob/8b6dfe17264a7ac9d3bda97de4f41205c78e5f15/ghcup-prereleases-0.0.8.yaml). The former does not contain an entry for GHC 9.10.1-alpha1, but the latter does. (I had to make a similar change in my local ~/.ghcup/config.yaml` file in order to be install GHC 9.10.1-alpha1 on my machine.)

**Comment by phadej** [comment]
Do you mind making a PR, I'm busy right now
