### ISSUE TITLE
What to do with older GHCs.

### ISSUE THREAD

**Issue by phadej** [haskell-CI/haskell-ci#719]
From https://wiki.ubuntu.com/Releases

Ubuntu Bionic (18.04) is EOL. On Ubuntu Focal (20.04) there are some GHC missing (there is GHC 7.0 and 7.2 in hvr ppa; and GHC-7.10+; in ghcup the GHC-7.10 is IIRC broken (required some post install patching). On Ubuntu Jammy there are only GHC-8.4+ (in `ghcup`, there are no hvr ppa for jammy).

Recently, GHA started warning about newer nodejs, forcing to update the action versions (`checkout`, `cache`). These work on `focal`, but don't on `bionic` (erroring with ``/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)``).

Even if it worked, Bionic is EOL.

So what to do?

A cleanest solution is to drop support for older GHCs. At least GHC-7. I think it's time, I have holding up with these for as long as possible, but now the issue is quite hardly forced.

So, soon, I will remove GHC-7 support from `haskell-ci`.

If you have comments, any good ideas, please comment.

Ping @RyanGlScott, as you are probably the only one running extensive CI setups with GHC-7. I only do because I could, but I'd be fine dropping GHC-7 support as I do sweep across packages updating for GHC-9.10.

--

GHC Version 8.0. 1 (released 21st May 2016), that's *a long time ago*.

**Comment by RyanGlScott** [comment]
I am fine with dropping GHC 7.* support. I've been expecting this to happen for a while now, and I agree that it's becoming increasingly hard to maintain support for these versions.
