### ISSUE TITLE
ghc=8.0.1 on debian stable : unrecognized relocation (0x2a) in section

### ISSUE THREAD

**Issue by erikd** [haskell-CI/haskell-ci#72]
@hvr Using your ghc-8.0.1 package on debian stable, I'm getting:
```
/usr/bin/ld: dist/dist-sandbox-3b597c82/build/P/Applicative.dyn_o: unrecognized
relocation (0x2a) in section `.text'
```
which looks exactly like https://ghc.haskell.org/trac/ghc/ticket/12147 . Pretty sure that fix when into 8.0.2.

**Comment by hvr** [comment]
@erikd did you use the one from http://downloads.haskell.org/debian/ ?

**Comment by erikd** [comment]
From memory, I ended up compiling one myself from source. using your ghc-8.0.1 package.

**Comment by hvr** [comment]
@erikd what's the easiest/quickest way to reproduce this?

**Comment by erikd** [comment]
If I was to reproduce it, I would set up a Debian Stable chroot, install GHC and cabal install from your ppa and then build HSOpenSSL in a sandbox (which is what I was trying to do).

**Comment by hvr** [comment]
@erikd just to be clear, did you ever use debian packages from http://downloads.haskell.org/debian/ ? or did you use packages compiled for Ubuntu (which are quite likely to have such subtle ABI issues when used on Debian)?

**Comment by erikd** [comment]
If I installed from a debian package I would do so from the official Debian repos rather than from haskell.org.

Anyway, I think we can close this.

**Comment by hvr** [comment]
fair enough :-)
