### ISSUE TITLE
Don't require `head.hackage` for GHC 9.10 by default

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#725]
Currently, generating a CI job for GHC 9.10 will cause it to use `head.hackage` by default:

```bash
          if [ $((HCNUMVER >= 91000)) -ne 0 ] ; then echo "HEADHACKAGE=true" >> "$GITHUB_ENV" ; else echo "HEADHACKAGE=false" >> "$GITHUB_ENV" ; fi
```

This is a consequence of this code:

https://github.com/haskell-CI/haskell-ci/blob/07deeb7c38a0d9e69a5f6defdac3818764a9164e/src/HaskellCI/HeadHackage.hs#L7-L8

Now that GHC 9.10.1 is fully released, should this be changed so that 9.10.1 doesn't require `head.hackage`, just like other full GHC releases?

**Comment by phadej** [comment]
Ouch. Thanks for spotting this! I'll make a fix asap.

**Comment by RyanGlScott** [comment]
Now that GHC 9.12.1 has been released, I think we need to do something similar by defining `defaultHeadHackage = C.orLaterVersion (C.mkVersion [9,13])`.
