### ISSUE TITLE
Make `any` constraints configurable

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-CI/haskell-ci#728]
After #727, `haskell-ci` uses `any` in all generated `installed` constraints. While I agree with this change in principle, in practice it prevents `cabal` from picking a build plan for one of my projects that uses a custom `Setup.hs` script. See https://github.com/haskell/cabal/issues/9917#issuecomment-2134882778.

Unfortunately, I am not aware of a workaround for this problem other than to remove the `any` constraint altogether. Would you agree to adding a `haskell-ci` configuration option that allows toggling the use of `any` in the generated constraints? (Perhaps it could be called `--installed-any` to mirror the existing `--installed` flag.) That way, I could work around this problem without needing to resort to patching the generated YAML file manually.

**Comment by phadej** [comment]
@RyanGlScott you can configure which dependencies are constraint with `installed:`. E.g. to disable it all together `installed: -all`, or selectively`installed: +all -Cabal`.

The https://github.com/haskell/cabal/issues/9917#issuecomment-2134882778 is however the true issue, and I'm not keen into working around `cabal-install` release management troubles.

**Comment by RyanGlScott** [comment]
Thanks, @phadej. I can confirm that adding `installed: +all -Cabal -Cabal-syntax` to my `cabal.haskell-ci` file suffices to work around the issue described in https://github.com/haskell/cabal/issues/9917#issuecomment-2134882778.
