### ISSUE TITLE
Debian 12 Bookworm Apt repository missing

### ISSUE THREAD

**Issue by veita** [haskell-CI/haskell-ci#731]
Debian Bookworm has been released at 2023-06-10. However, https://downloads.haskell.org/debian/ does not have a Bookworm repository yet. Are there plans to provide one?

**Comment by phadej** [comment]
The  https://downloads.haskell.org/debian/ was maintained by Herbert, who isn't active anymore. So

> Are there plans to provide one?

there aren't.
