### ISSUE TITLE
cabal-install versions not most current

### ISSUE THREAD

**Issue by ysangkok** [haskell-CI/haskell-ci#732]
Looking at [Cabal.hs](https://github.com/haskell-CI/haskell-ci/blob/master/src/HaskellCI/Cabal.hs), it seems that 3.10.2.0 is used when 3.10.3.0 could be used instead.

Also, 3.8 is not present, why?

Also, 3.6.2.0 is used even though GHCup has 3.6.2.0-p1 available with some patch applied. Is the p1 representable in Haskell-CI?

I am having a hard time understanding what this mapping is supposed to target.

EDIT: cabal-install-3.12.1.0 is now available in GHCup, so that could be added too

**Comment by phadej** [comment]
To clarify the commit closing this issue: The mapping in `Cabal` module was there to map short versions to long ones for GHCUP, e.g. from `3.10` to `3.10.2.0`.

> I am having a hard time understanding what this mapping is supposed to target.

The mapping was above. `hvr-ppa` had packages named `cabal-install-3.0`, `cabal-install-3.2` etc, and you got the most recent in the series through those. The mapping from short to full versions was needed for ghcup.

> Also, 3.8 is not present, why?

I guess, it wasn't ever used. I don't remember which `cabal-install` issue was blocking it. (https://github.com/haskell-CI/haskell-ci/pull/606 wasn't merged, and we jumped to 3.9.0.0)

> Also, 3.6.2.0 is used even though GHCup has 3.6.2.0-p1 available with some patch applied

The `p1` version is not representable with `Version` datatype, it's not worth patching it. (ALso I have no idea what's the change in p1, which lessens the motivation)

> EDIT: cabal-install-3.12.1.0 is now available in GHCup, so that could be added too

It will be. But you can also specify `cabal-install-version: 3.12.1.0` if you wish.
