### ISSUE TITLE
Question: Is it possible to specify `test-options` for `v2-test`?

### ISSUE THREAD

**Issue by meooow25** [haskell-CI/haskell-ci#743]
I don't see a way to do this, is it possible?  
In this case I want CI to run tests with args like `--quickcheck-tests=1000`

**Comment by phadej** [comment]
This is more of a `tasty` problem (I assume you are using `tasty`). You want to supply different defaults, seems there is an issue about that https://github.com/UnkindPartition/tasty/issues/414

**Comment by meooow25** [comment]
I am using tasty, but I don't see this as a tasty problem. If I were using hspec I would have to use `--qc-max-success=1000` instead. And there could be other reasons to provide args too, quickcheck is just what I want to deal with at the moment.

**Comment by phadej** [comment]
I consider providing options in `haskell-ci` as an anti-pattern. In a multi-package / multi test-suite setting it's not well behaved. It's an `cabal` cli interface problem. A work-around solution is to have sane defaults, so CI doesn't need any options.
