### ISSUE TITLE
use buildpack-deps:22.04 etc instead of jammy?

### ISSUE THREAD

**Issue by juhp** [haskell-CI/haskell-ci#744]
Just curious why `buildpack-deps:jammy` is used everywhere: shouldn't it be the same tag as the `ubuntu:2*.04` ?
Anyway apparently it works anyway so shrug I guess.

(I have my own [minimalist GHA](https://github.com/juhp/select-rpms/blob/main/.github/workflows/build.yml), but ran into a [project](https://github.com/glguy/config-value/pull/14) that was still using `buildpack-deps:bionic` the other day.)

**Comment by phadej** [comment]
I like codenames more.
