### ISSUE TITLE
How to enable warnings?

### ISSUE THREAD

**Issue by neongreen** [haskell-CI/haskell-ci#95]
I want warnings to be enabled on Travis but I don't to impose `-Werror` upon all my users – only Travis. How should I modify the generated travis.yml? I tried modifying the last invocation of `cabal new-build`, but it enabled warnings for all dependencies too, not just for my library ([build log](https://travis-ci.org/aelve/quickcheck-predicates/jobs/277650588#L622)):

```diff
  # build & run tests, build benchmarks
- - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+ - cabal new-build --ghc-options=-Werror -w ${HC} ${TEST} ${BENCH} all
```

**Comment by phadej** [comment]
you can do something like

```sh
echo "package $PKGNAME" >> cabal.project
echo "  ghc-options: -Wall -Werror" >> cabal.project
```

**Comment by phadej** [comment]
There is `local-ghc-options` configuration, this package itself uses it.
